import {definePlugin, type MessageEnvelope, type PluginContext} from "telebox/sdk";
import {setTimeout as sleep} from "node:timers/promises";

const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]!);
const help=(p:string)=>`🧹 <b>清理工具 Pro</b>\n\n<code>${esc(p)}clean deleted pm [rm]</code>\n<code>${esc(p)}clean deleted member [rm]</code>\n<code>${esc(p)}clean blocked pm [all]</code>\n<code>${esc(p)}clean blocked member [all]</code>\n\n智能模式跳过机器人、诈骗和虚假账户。`;
const err=(e:unknown)=>String((e as any)?.message??e);
const wait=async(e:unknown,signal:AbortSignal)=>{const m=err(e).match(/FLOOD_WAIT[_ ]?(\d+)/);if(!m)return false;await sleep((Number(m[1])+1)*1000,undefined,{signal});return true;};
const group=(m:MessageEnvelope)=>(m.raw as any)?.isGroup||(m.raw as any)?.isChannel||m.chatId.startsWith("-");

async function permission(client:any,chat:any,Api:any){try{const me=await client.getMe();if(chat.className==="Chat")return !!chat.creator||!!chat.adminRights;const p=(await client.invoke(new Api.channels.GetParticipant({channel:chat,participant:me.id}))).participant;return p?.className==="ChannelParticipantCreator"||(p?.className==="ChannelParticipantAdmin"&&!!p.adminRights?.banUsers);}catch{return false;}}
async function deletedPm(message:MessageEnvelope,remove:boolean,ctx:PluginContext){await ctx.telegram.edit(message,remove?"🔍 正在扫描并从对话列表中移除已注销账号...":"🔍 正在扫描私聊已注销账号...");await ctx.telegram.withClient(async(client:any,signal)=>{const found=new Map<string,any>();for(const folder of [0,1]){try{for await(const d of client.iterDialogs({folder})){signal.throwIfAborted();if(d.isUser&&d.entity?.className==="User"&&d.entity.deleted)found.set(String(d.entity.id),d);}}catch{ctx.log.error("clean:dialogs",{folder});}}
  let ok=0,failed=0;if(remove)for(const d of found.values()){try{await client.deleteDialog(d.inputEntity);ok++;await sleep(150,undefined,{signal});}catch(e){if(await wait(e,signal)){try{await client.deleteDialog(d.inputEntity);ok++;}catch{failed++;}}else failed++;}}
  const rows=[...found.keys()].slice(0,15).map(id=>`• <a href="tg://user?id=${esc(id)}">已注销账号</a> (ID: <code>${esc(id)}</code>)`).join("\n");const title=remove?"清理完成":"扫描完成";await ctx.telegram.edit(message,found.size?`✅ <b>${title}</b>\n\n共找到 <code>${found.size}</code> 个已注销对话${remove?`，成功移除 <code>${ok}</code>${failed?`，失败 <code>${failed}</code>`:""}`:""}:\n\n${rows}${found.size>15?`\n... 以及其他 ${found.size-15} 个会话`:""}`:`✅ <b>${title}</b>\n\n对话列表中未发现已注销账号。`,{parseMode:"html"});});}
async function deletedMembers(message:MessageEnvelope,remove:boolean,ctx:PluginContext){if(!group(message)){await ctx.telegram.edit(message,"❌ <b>错误:</b> 此命令仅在群组中可用",{parseMode:"html"});return;}await ctx.telegram.withClient(async(client:any,signal)=>{const {Api}=await import("teleproto");const raw:any=message.raw,chat=await client.getEntity(raw?.peerId??message.chatId),input=await client.getInputEntity(chat);if(remove&&!await permission(client,chat,Api)){await ctx.telegram.edit(message,"❌ <b>错误:</b> 没有封禁用户权限，无法执行清理",{parseMode:"html"});return;}await ctx.telegram.edit(message,remove?"🔍 正在扫描并清理群组已注销账号...":"🔍 正在扫描群组已注销账号...");let found=0,ok=0,failed=0;const ids:string[]=[];for await(const user of client.iterParticipants(chat)){signal.throwIfAborted();if(user.className!=="User"||!user.deleted)continue;found++;ids.push(String(user.id));if(remove)try{const target=await client.getInputEntity(user);if(chat.className==="Chat")await client.invoke(new Api.messages.DeleteChatUser({chatId:chat.id,userId:target,revokeHistory:false}));else{await client.invoke(new Api.channels.EditBanned({channel:input,participant:target,bannedRights:new Api.ChatBannedRights({viewMessages:true,untilDate:0})}));await client.invoke(new Api.channels.EditBanned({channel:input,participant:target,bannedRights:new Api.ChatBannedRights({untilDate:0})}));}ok++;}catch(e){failed++;if(await wait(e,signal))ctx.log.info("clean:flood-resumed");}await sleep(150,undefined,{signal});}
  const list=ids.slice(0,15).map(id=>`• <a href="tg://user?id=${esc(id)}">${esc(id)}</a>`).join("\n");await ctx.telegram.edit(message,found?`✅ <b>${remove?"清理":"扫描"}完成</b>\n\n发现 <code>${found}</code> 个已注销账号${remove?`\n成功移出 <code>${ok}</code> 个${failed?` · 失败 <code>${failed}</code> 个`:""}`:""}:\n\n${list}${found>15?`\n... 还有 ${found-15} 个未显示`:""}`:`✅ <b>扫描完成</b>\n\n此群组中没有发现已注销账号。`,{parseMode:"html"});});}
async function blockedPm(message:MessageEnvelope,all:boolean,ctx:PluginContext){await ctx.telegram.edit(message,`🧹 开始清理拉黑用户\n\n模式: ${all?"全量清理":"智能清理"}`);await ctx.telegram.withClient(async(client:any,signal)=>{const {Api}=await import("teleproto");let offset=0,total=0;const users:any[]=[];while(true){const r:any=await client.invoke(new Api.contacts.GetBlocked({offset,limit:100}));const page=r.users||[];users.push(...page);total=Number(r.count??users.length);if(page.length<100||users.length>=total)break;offset+=page.length;}let ok=0,failed=0,skipped=0,processed=0;for(const user of users){signal.throwIfAborted();processed++;if(!all&&(user.bot||user.scam||user.fake)){skipped++;continue;}try{await client.invoke(new Api.contacts.Unblock({id:user}));ok++;}catch(e){if(await wait(e,signal)){try{await client.invoke(new Api.contacts.Unblock({id:user}));ok++;}catch{failed++;}}else failed++;}if(processed%10===0)await ctx.telegram.edit(message,`🧹 <b>清理拉黑用户进行中</b>\n\n进度: ${processed}/${total}\n成功: ${ok} · 失败: ${failed} · 跳过: ${skipped}`,{parseMode:"html"});await sleep(all?1000:200,undefined,{signal});}await ctx.telegram.edit(message,`✅ <b>清理拉黑用户完成</b>\n\n总计用户: ${total}\n成功清理: ${ok}\n清理失败: ${failed}\n跳过处理: ${skipped}\n清理模式: ${all?"全量清理":"智能清理"}`,{parseMode:"html"});});}
async function blockedMembers(message:MessageEnvelope,all:boolean,ctx:PluginContext){if(!group(message)){await ctx.telegram.edit(message,"❌ <b>错误:</b> 此命令只能在群组中使用",{parseMode:"html"});return;}await ctx.telegram.withClient(async(client:any,signal)=>{const {Api}=await import("teleproto");const raw:any=message.raw,chat=await client.getEntity(raw?.peerId??message.chatId);if(chat.className!=="Channel"){await ctx.telegram.edit(message,"❌ 基本群不支持封禁列表");return;}if(!await permission(client,chat,Api)){await ctx.telegram.edit(message,"❌ <b>错误:</b> 没有封禁用户权限",{parseMode:"html"});return;}const me=await client.getMe(),input=await client.getInputEntity(chat),targets:any[]=[],users=new Map<string,any>();let offset=0;while(true){const r:any=await client.invoke(new Api.channels.GetParticipants({channel:input,filter:new Api.ChannelParticipantsKicked({q:""}),offset,limit:200,hash:0 as any}));for(const u of r.users||[])users.set(String(u.id),u);const page=r.participants||[];targets.push(...page.filter((p:any)=>all||String(p.kickedBy)===String(me.id)));if(page.length<200)break;offset+=page.length;}let ok=0,failed=0;for(const p of targets){signal.throwIfAborted();try{const u=users.get(String(p.peer?.userId??p.userId))??p.peer??p.userId;await client.invoke(new Api.channels.EditBanned({channel:input,participant:await client.getInputEntity(u),bannedRights:new Api.ChatBannedRights({untilDate:0})}));ok++;}catch{failed++;}await sleep(500,undefined,{signal});}await ctx.telegram.edit(message,targets.length?`✅ <b>解封完成</b>\n\n成功: <code>${ok}</code> 个\n失败: <code>${failed}</code> 个`:"ℹ️ 没有找到需要解封的实体",{parseMode:"html"});});}

export default function createClean(){return definePlugin({apiVersion:1,id:"clean",description:"清理已注销账号、拉黑用户和群组封禁",commands:{clean:{description:"账号与封禁清理",ignoreEdited:true,async handle({message,args,prefix},ctx){try{const kind=args[0]?.toLowerCase(),scope=args[1]?.toLowerCase(),mode=args[2]?.toLowerCase();if(!kind||["help","h"].includes(kind)){await ctx.telegram.edit(message,help(prefix),{parseMode:"html"});return;}if(kind==="deleted"&&scope==="pm")await deletedPm(message,mode==="rm",ctx);else if(kind==="deleted"&&scope==="member")await deletedMembers(message,mode==="rm",ctx);else if(kind==="blocked"&&scope==="pm")await blockedPm(message,mode==="all",ctx);else if(kind==="blocked"&&scope==="member")await blockedMembers(message,mode==="all",ctx);else await ctx.telegram.edit(message,`❌ <b>错误:</b> ${scope?`未知类型: ${esc(scope)}`:"请指定清理类型: pm 或 member"}`,{parseMode:"html"});}catch(e){if(!ctx.signal.aborted)await ctx.telegram.edit(message,err(e).includes("FLOOD_WAIT")?"⏳ 请求过于频繁，请稍后重试":`❌ <b>操作失败:</b> ${esc(err(e))}`,{parseMode:"html"});}}}}});}
