import {open, readFile} from "node:fs/promises";
import path from "node:path";
import {STRUCTURED_PLUGIN_API_VERSION, renderCommandHelp, type CommandDefinition, definePlugin, type PluginContext} from "telebox/sdk";
import type {Api} from "teleproto";

const PROXIES=["i.pximg.net","i.pixiv.cat","i.pixiv.re","i.pixiv.nl"] as const;
const MAX_IMAGE=25*1024*1024;
type State={schemaVersion:1;proxyHost:string;legacyImported:boolean;[key:string]:unknown};
const DEFAULTS:State={schemaVersion:1,proxyHost:"i.pximg.net",legacyImported:false};
const store=(c:PluginContext)=>c.storage.json<State>("v2-config.json",DEFAULTS);
const esc=(v:unknown)=>String(v??"").replace(/[&<>\"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;"})[x]!);
const validProxy=(v:unknown):v is typeof PROXIES[number]=>typeof v==="string"&&(PROXIES as readonly string[]).includes(v);
async function responseJson(response:Response,signal:AbortSignal){if(response.status!==200)throw new Error("API 状态异常");const type=response.headers.get("content-type")??"";if(type&&!type.toLowerCase().includes("json"))throw new Error("API 格式异常");if(Number(response.headers.get("content-length"))>1024*1024)throw new Error("API 响应过大");if(!response.body)throw new Error("API 响应为空");const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{for(;;){signal.throwIfAborted();const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>1024*1024)throw new Error("API 响应过大");chunks.push(part.value);}return JSON.parse(Buffer.concat(chunks,size).toString("utf8"));}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}}
function normalize(raw:unknown):State{const x=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};const legacy=x.zpr_proxy_host;return {...x,schemaVersion:1,proxyHost:validProxy(x.proxyHost)?x.proxyHost:validProxy(legacy)?legacy:"i.pximg.net",legacyImported:x.legacyImported===true};}
async function migrate(c:PluginContext){let value=normalize(await store(c).read());if(!value.legacyImported){try{const raw=JSON.parse(await c.tasks.run("zpr:legacy-read",()=>readFile(c.files.dataPath("zpr_config.json"),"utf8")));if(value.proxyHost==="i.pximg.net")value.proxyHost=normalize(raw).proxyHost;}catch{}value.legacyImported=true;}return store(c).update(()=>value);}
function apiItem(value:unknown){if(!value||typeof value!=="object")return;const x=value as any;if(!Number.isSafeInteger(x.pid)||typeof x.title!=="string"||!Number.isSafeInteger(x.width)||!Number.isSafeInteger(x.height)||!x.urls||typeof x.urls.regular!=="string"||typeof x.urls.original!=="string")return;return{pid:x.pid as number,title:x.title.slice(0,500) as string,width:x.width as number,height:x.height as number,regular:x.urls.regular as string,original:x.urls.original as string};}
function imageUrl(raw:string,proxy:string){let u:URL;try{u=new URL(raw);}catch{throw new Error("图片地址无效");}if(u.protocol!=="https:"||u.username||u.password||u.hash)throw new Error("图片地址无效");u.hostname=proxy;u.port="";return u;}
function publicUrl(raw:string){let u:URL;try{u=new URL(raw);}catch{throw new Error("原图地址无效");}if(u.protocol!=="https:"||u.username||u.password||u.hash||!["pximg.net","pixiv.net","pixiv.cat","pixiv.re","pixiv.nl"].some(h=>u.hostname===h||u.hostname.endsWith(`.${h}`)))throw new Error("原图地址无效");return u.href;}
async function image(c:PluginContext,url:URL,host:string,target:string){return c.http.withResponse(url,{method:"GET",redirect:"manual",credentials:"omit",headers:{Accept:"image/*","User-Agent":"MiBot-Zpr/2.0",...(host==="i.pximg.net"?{Referer:"https://www.pixiv.net/"}:{})}},async(response,signal)=>{if(response.status!==200||!response.body)throw new Error("图片不可用");const type=response.headers.get("content-type")??"";if(type&&!type.toLowerCase().startsWith("image/"))throw new Error("图片格式无效");const reader=response.body.getReader(),handle=await open(target,"wx",0o600);let total=0;try{for(;;){signal.throwIfAborted();const chunk=await reader.read();if(chunk.done)break;total+=chunk.value.byteLength;if(total>MAX_IMAGE)throw new Error("图片过大");await handle.write(chunk.value);}if(!total)throw new Error("图片为空");}finally{await reader.cancel().catch(()=>{});reader.releaseLock();await handle.close();}},{timeoutMs:30_000,signal:c.signal,redirects:{allowedHosts:[host],maxRedirects:2}});}
async function download(c:PluginContext,item:NonNullable<ReturnType<typeof apiItem>>,preferred:string,target:string){for(const host of [preferred,...PROXIES.filter(x=>x!==preferred)]){c.signal.throwIfAborted();try{await image(c,imageUrl(item.regular,host),host,target);return host;}catch{c.signal.throwIfAborted();try{await (await import("node:fs/promises")).unlink(target);}catch{}}}throw new Error("图片下载失败");}
const guarded = (operation: (i: Parameters<CommandDefinition["handle"]>[0], c: PluginContext, state: State, edit: (text: string, html?: boolean) => Promise<void>) => Promise<void>): CommandDefinition["handle"] => async (i, c) => {
  const edit = (text: string, html = false) => c.telegram.edit(i.message, text, html ? {parseMode: "html", linkPreview: false} : {});
  try {
    if (["help", "h"].includes(i.args[0]?.toLowerCase() ?? "") && !i.subcommand) { await edit(help(i.prefix), true); return; }
    await operation(i, c, normalize(await store(c).read()), edit);
  } catch { if (c.signal.aborted) return; c.log.error("zpr_failed"); await edit("获取图片失败，请检查网络或稍后重试"); }
};
const command: CommandDefinition = {
  description: "随机纸片人图片", helpArgs: ["help", "h"], args: "[标签] [1–10] [r18]", subcommandsCaseSensitive: false,
  examples: [{args: "", description: "随机获取 1 张"}, {args: "3"}, {args: "风景"}, {args: "风景 2"}, {args: "r18 2", description: "以剧透方式发送 R18 图片"}],
  subcommands: {proxy: {description: "查看或设置图片反代", args: "[地址]", examples: PROXIES.map(host => ({args: `proxy ${host}`})), help: [{body: "默认 i.pximg.net，可选 " + PROXIES.join("、") + "。首选下载失败时尝试其余地址，成功后保存可用地址。"}], handle: guarded(async (i, c, state, edit) => {
if(!i.args[0]){await edit(`当前反代：${state.proxyHost}\n可用：${PROXIES.join("、")}`);return;}if(!validProxy(i.args[0]))throw new Error("反代地址不在允许列表");state=await store(c).update(v=>({...normalize(v),proxyHost:i.args[0]!,legacyImported:true}));await edit(`反代已更新：${state.proxyHost}`);return;  })}},
  help: [{heading: "图片来源与范围：", body: "从 Lolicon API 获取 Pixiv 图片，默认 1 张，最多 10 张，只取第一个标签参数。单张下载最多 25 MiB，发送作品标题、原图链接和尺寸；成功后删除命令消息。"}],
  handle: guarded(async (i, c, state, edit) => {
  let count=1,r18=0,tag="";for(const arg of i.args){if(arg.toLowerCase()==="r18")r18=1;else if(/^\d+$/u.test(arg))count=Math.min(10,Math.max(1,Number(arg)));else if(!tag)tag=arg.slice(0,100);}await edit("正在获取图片…");
  const query=new URL("https://api.lolicon.app/setu/v2");for(const[k,v]of Object.entries({num:String(count),r18:String(r18),tag,size:"regular",proxy:state.proxyHost,excludeAI:"true"}))query.searchParams.append(k,v);query.searchParams.append("size","original");
  const data=await c.http.withResponse(query,{method:"GET",redirect:"manual",credentials:"omit",headers:{Accept:"application/json","User-Agent":"MiBot-Zpr/2.0"}},responseJson,{timeoutMs:10_000,signal:c.signal,redirects:{allowedHosts:["api.lolicon.app"],maxRedirects:2}}) as any;
  if(!Array.isArray(data?.data))throw new Error("API 响应无效");const items=data.data.map(apiItem).filter(Boolean).slice(0,count) as NonNullable<ReturnType<typeof apiItem>>[];if(!items.length)throw new Error("未找到图片");
  await c.files.withTemp(async directory=>{const results:{item:NonNullable<ReturnType<typeof apiItem>>;file:string;host:string}[]=[];for(const item of items){const file=path.join(directory,`${item.pid}.jpg`);results.push({item,file,host:await download(c,item,state.proxyHost,file)});}const best=results.find(x=>x.host!==state.proxyHost)?.host;if(best)await store(c).update(v=>({...normalize(v),proxyHost:best,legacyImported:true}));
  await c.telegram.withClient(async client=>{const raw=i.message.raw as Api.Message|undefined;if(!raw?.peerId)throw new Error("消息上下文不可用");for(const {item,file} of results){c.signal.throwIfAborted();const original=publicUrl(item.original);await client.sendFile(raw.peerId,{file,caption:`<b>🎨 ${esc(item.title)}</b>\n🆔 <a href="https://www.pixiv.net/artworks/${item.pid}">${item.pid}</a>\n🔗 <a href="${esc(original)}">原图</a>\n📐 <code>${item.width}×${item.height}</code>`,parseMode:"html",spoiler:r18===1,replyTo:i.message.topicId??i.message.replyToId});}if(typeof raw.delete==="function")await raw.delete({revoke:true});});});
  }),
};
const help = (prefix: string) => renderCommandHelp("zpr", command, {prefix, title: "🎨 随机纸片人"});
export default function createZpr() { return definePlugin({renderHelp: help, apiVersion: STRUCTURED_PLUGIN_API_VERSION, id: "zpr", description: "从 Lolicon API 获取随机 Pixiv 图片", commands: {zpr: command},
settings:c=>({id:"zpr",title:"随机纸片人",description:"Lolicon 图片反代配置",category:"插件配置",icon:"🎨",getSchema:()=>[{key:"proxyHost",label:"反代服务器",type:"select",options:PROXIES.map(value=>({value,label:value}))}],getValues:async()=>({proxyHost:(await store(c).read()).proxyHost}),async setValues(patch){if(!validProxy(patch.proxyHost))throw new Error("invalid proxy");await store(c).update(v=>({...normalize(v),proxyHost:patch.proxyHost as string,legacyImported:true}));}}),async setup(c){await migrate(c);}});}
