import {readFile} from "node:fs/promises";
import {definePlugin, type PluginContext} from "telebox/sdk";

type ProviderType = "openai" | "gemini";
type AuthMethod = "bearer_token" | "api_key_header" | "query_param";
type Provider = {name:string;baseUrl:string;apiKey:string;model:string;type:ProviderType;authMethod:AuthMethod};
type State = {schemaVersion:1;providers:Record<string,Provider>;defaultProvider:string|null;prompts:Record<string,string>;timeoutMs:number;collapse:boolean;legacyImported:boolean;[key:string]:unknown};
const DEFAULTS:State={schemaVersion:1,providers:{},defaultProvider:null,prompts:{},timeoutMs:120_000,collapse:true,legacyImported:false};
const BUILTIN:Readonly<Record<string,string>>={zj:"请总结以下消息的主要内容，提取关键信息，用简洁的中文回复：",fx:"请分析以下消息的观点、态度和倾向，用简洁的中文回复："};
const store=(c:PluginContext)=>c.storage.json<State>("v2-config.json",DEFAULTS);
const esc=(v:unknown)=>String(v??"").replace(/[&<>\"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;"})[x]!);
async function responseJson(response:Response,signal:AbortSignal){if(response.status<200||response.status>=300)throw new Error("上游状态异常");const type=response.headers.get("content-type")??"";if(type&&!type.toLowerCase().includes("json"))throw new Error("上游格式异常");if(Number(response.headers.get("content-length"))>2*1024*1024)throw new Error("上游响应过大");if(!response.body)return{};const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{for(;;){signal.throwIfAborted();const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>2*1024*1024)throw new Error("上游响应过大");chunks.push(part.value);}return JSON.parse(Buffer.concat(chunks,size).toString("utf8"));}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}}

function endpoint(value:string):URL {
  let url:URL; try{url=new URL(value);}catch{throw new Error("API 地址无效");}
  if(url.protocol!=="https:"||url.username||url.password||url.hash||url.search||!url.hostname||url.port)throw new Error("API 地址必须是无凭据的 HTTPS 地址");
  url.pathname=url.pathname.replace(/\/+$/u,"");
  return url;
}
function provider(value:unknown,name?:string):Provider|undefined{
  if(!value||typeof value!=="object")return;
  const x=value as Record<string,unknown>,type=x.type==="gemini"?"gemini":x.type==="openai"?"openai":undefined;
  const auth=x.authMethod??x.auth_method;
  if(!type||typeof (x.baseUrl??x.base_url)!=="string"||typeof (x.apiKey??x.api_key)!=="string"||typeof x.model!=="string")return;
  const authMethod:AuthMethod=auth==="api_key_header"||auth==="query_param"||auth==="bearer_token"?auth:(type==="gemini"?"query_param":"bearer_token");
  const result:Provider={name:String(x.name??name??"").slice(0,64),baseUrl:String(x.baseUrl??x.base_url),apiKey:String(x.apiKey??x.api_key),model:String(x.model).slice(0,128),type,authMethod};
  if(!result.name||!result.apiKey||!result.model)return; endpoint(result.baseUrl); return result;
}
function normalize(raw:unknown):State{
  const x=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};const providers:Record<string,Provider>={};
  if(x.providers&&typeof x.providers==="object")for(const[name,value]of Object.entries(x.providers)){const p=provider(value,name);if(p)providers[p.name]=p;}
  const prompts:Record<string,string>={};if(x.prompts&&typeof x.prompts==="object")for(const[k,v]of Object.entries(x.prompts)){if(/^[\w-]{1,32}$/u.test(k)&&typeof v==="string"&&v.length<=10_000)prompts[k]=v;}
  const candidate=String(x.defaultProvider??x.default_provider??"");
  return {...x,schemaVersion:1,providers,defaultProvider:providers[candidate]?candidate:Object.keys(providers)[0]??null,prompts,
    timeoutMs:Math.min(300_000,Math.max(10_000,Number(x.timeoutMs??x.timeout??120_000)||120_000)),collapse:x.collapse!==false,legacyImported:x.legacyImported===true};
}
async function migrate(c:PluginContext){let current=normalize(await store(c).read());if(!current.legacyImported){try{const text=await c.tasks.run("uai:legacy-read",()=>readFile(c.files.dataPath("config.json"),"utf8"));const legacy=normalize(JSON.parse(text));current=normalize({...current,...legacy,providers:{...legacy.providers,...current.providers},prompts:{...legacy.prompts,...current.prompts}});}catch{}current.legacyImported=true;}return store(c).update(()=>current);}
function help(p:string){return `<b>UAI 用户消息分析</b>\n<code>${esc(p)}uai zj [数量|2h]</code> · <code>fx</code>\n<code>${esc(p)}uai add 名称 URL KEY openai|gemini</code>（仅收藏夹）\n<code>${esc(p)}uai set|del|model|list</code> · <code>prompt add|del|list</code> · <code>collapse on|off</code>`;}
const id=(v:any):string=>v===undefined||v===null?"":typeof v==="object"?id(v.userId??v.channelId??v.chatId??v.value):String(v);
function limit(args:readonly string[]){let result:{kind:"count";value:number}|{kind:"time";value:number}|{kind:"today"}={kind:"today"};for(const arg of args){if(/^\d+$/u.test(arg))result={kind:"count",value:Math.min(500,Math.max(1,Number(arg)))};else{const m=/^(\d+)([hm])$/iu.exec(arg);if(m)result={kind:"time",value:Math.min(7*86400,Number(m[1])*(m[2].toLowerCase()==="h"?3600:60))};}}return result;}
async function collect(c:PluginContext,peer:any,sender:string|null,rule:ReturnType<typeof limit>){return c.telegram.withClient(async client=>{const now=Math.floor(Date.now()/1000),start=rule.kind==="today"?new Date().setHours(0,0,0,0)/1000:rule.kind==="time"?now-rule.value:0;const maximum=rule.kind==="count"?rule.value:500;const options:any={limit:sender?Math.min(maximum*20,3000):maximum};if(sender)try{options.fromUser=await client.getEntity(sender);}catch{}const output:string[]=[];let characters=0;for await(const value of client.iterMessages(peer,options)){c.signal.throwIfAborted();const m:any=value;if(rule.kind!=="count"&&Number(m.date)<start)break;if(sender&&!options.fromUser&&id(m.senderId)!==sender)continue;if(typeof m.message!=="string"||!m.message||/^📊 (分析|总结)结果/u.test(m.message))continue;const who=String(m.sender?.firstName??m.sender?.username??"未知"),line=`[${new Date(Number(m.date)*1000).toISOString().slice(0,16).replace("T"," ")}] ${who}: ${m.message}`;if(characters+line.length>100_000)break;characters+=line.length;output.push(line);if(output.length>=maximum)break;}return output.reverse();});}
async function ai(c:PluginContext,p:Provider,prompt:string,content:string,timeoutMs:number){const base=endpoint(p.baseUrl),headers:Record<string,string>={"content-type":"application/json"};let target:URL,body:unknown;
  if(p.type==="gemini"){target=new URL(`${base.pathname}/v1beta/models/${encodeURIComponent(p.model)}:generateContent`,base.origin);if(p.authMethod==="api_key_header")headers["x-goog-api-key"]=p.apiKey;else target.searchParams.set("key",p.apiKey);body={contents:[{role:"user",parts:[{text:`${prompt}\n\n${content}`}]}]};}
  else{target=new URL(`${base.pathname}${/\/v\d+$/u.test(base.pathname)?"":"/v1"}/chat/completions`,base.origin);if(p.authMethod==="api_key_header")headers["x-api-key"]=p.apiKey;else if(p.authMethod==="query_param")target.searchParams.set("key",p.apiKey);else headers.authorization=`Bearer ${p.apiKey}`;body={model:p.model,messages:[{role:"user",content:`${prompt}\n\n${content}`}],max_tokens:4096};}
  const data=await c.http.withResponse(target,{method:"POST",redirect:"manual",credentials:"omit",headers,body:JSON.stringify(body)},responseJson,{timeoutMs,signal:c.signal,redirects:{allowedHosts:[target.hostname],maxRedirects:2}}) as any;
  const text=p.type==="gemini"?data?.candidates?.[0]?.content?.parts?.map((x:any)=>typeof x?.text==="string"?x.text:"").join(""):data?.choices?.[0]?.message?.content;if(typeof text!=="string"||!text.trim())throw new Error("无有效响应");return text.trim();}

export default function createUai(){return definePlugin({apiVersion:1,id:"uai",description:"引用消息并使用 AI 汇总或分析历史消息",commands:{uai:{description:"AI 汇总或分析引用来源",async handle(i,c){const edit=(text:string,html=false)=>c.telegram.edit(i.message,text,html?{parseMode:"html",linkPreview:false}:{});const [sub,...rest]=i.args;try{
  if(!sub||sub==="help"||sub==="h"){await edit(help(i.prefix),true);return;}let state=normalize(await store(c).read());
  if(sub==="add"){if(!i.message.saved){await edit("API Key 配置仅限收藏夹");return;}if(rest.length<4)throw new Error("用法：uai add 名称 URL KEY openai|gemini");const[name,url,key,typeRaw]=rest,type=typeRaw as ProviderType;if(type!=="openai"&&type!=="gemini")throw new Error("类型必须是 openai 或 gemini");const p=provider({name,baseUrl:url,apiKey:key,type,model:type==="gemini"?"gemini-2.0-flash":"gpt-4o"});if(!p)throw new Error("供应商配置无效");await store(c).update(v=>normalize({...v,providers:{...normalize(v).providers,[name]:p},defaultProvider:normalize(v).defaultProvider??name,legacyImported:true}));await edit(`供应商 ${name} 已添加`);return;}
  if(sub==="del"){const name=rest[0];if(!name||!state.providers[name])throw new Error("供应商不存在");delete state.providers[name];state.defaultProvider=state.defaultProvider===name?Object.keys(state.providers)[0]??null:state.defaultProvider;await store(c).update(()=>state);await edit("供应商已删除");return;}
  if(sub==="set"||sub==="model"){const name=rest[0];if(!name||!state.providers[name])throw new Error("供应商不存在");if(sub==="set")state.defaultProvider=name;else{if(!rest[1])throw new Error("请提供模型");state.providers[name]={...state.providers[name],model:rest[1]};}await store(c).update(()=>state);await edit("配置已更新");return;}
  if(sub==="list"){await edit(Object.values(state.providers).map(p=>`${p.name}${p.name===state.defaultProvider?" *":""} (${p.type}, ${p.model})`).join("\n")||"暂无供应商");return;}
  if(sub==="collapse"){if(rest[0]!=="on"&&rest[0]!=="off")throw new Error("用法：collapse on|off");await store(c).update(v=>normalize({...v,collapse:rest[0]==="on"}));await edit("折叠设置已更新");return;}
  if(sub==="prompt"){const[action,name,...words]=rest;if(action==="list"){await edit([...Object.keys(BUILTIN),...Object.keys(state.prompts)].join("\n"));return;}if(!name||BUILTIN[name])throw new Error("提示词名称无效");if(action==="add"&&words.join(" "))state.prompts[name]=words.join(" ").slice(0,10_000);else if(action==="del")delete state.prompts[name];else throw new Error("用法：prompt add|del|list");await store(c).update(()=>state);await edit("提示词已更新");return;}
  const reply=await c.telegram.getReply(i.message);if(!reply)throw new Error("请引用一条消息");const raw:any=i.message.raw,replyRaw:any=reply.raw;if(!raw?.peerId||!replyRaw)throw new Error("消息上下文不可用");let source:string|null=id(replyRaw.senderId),peer:any=raw.peerId,name=String(replyRaw.sender?.firstName??replyRaw.sender?.username??"用户");const forwarded=replyRaw.fwdFrom?.fromId;if(forwarded?.channelId){source=null;peer=`-100${id(forwarded.channelId)}`;name="频道";}else if(forwarded?.userId)source=id(forwarded.userId);if(!source&&!(forwarded?.channelId))throw new Error("无法确定消息来源");
  const promptKey=Object.hasOwn(BUILTIN,sub)||Object.hasOwn(state.prompts,sub)?sub:"zj";const messages=await collect(c,peer,source,limit(i.args));if(!messages.length)throw new Error("没有找到消息");const selected=state.defaultProvider&&state.providers[state.defaultProvider];if(!selected)throw new Error("请先配置 AI 供应商");await edit("正在分析消息…");const result=await ai(c,selected,state.prompts[promptKey]??BUILTIN[promptKey]??BUILTIN.zj!,`${name}\n\n${messages.join("\n")}`,state.timeoutMs);const points=Array.from(result),content=esc(points.length>3000?`${points.slice(0,3000).join("")}\n…（输出已截断）`:result);await edit(`📊 <b>${promptKey==="fx"?"分析":"总结"}结果</b>（${esc(name)}，${messages.length} 条）\n\n${state.collapse?`<blockquote expandable>${content}</blockquote>`:content}`,true);
 }catch{if(c.signal.aborted)return;c.log.error("uai_failed");await edit("UAI 执行失败，请检查配置、引用消息和网络");}}}},settings:c=>({id:"uai",title:"UAI",description:"AI 消息分析供应商与提示词",category:"插件配置",icon:"🤖",getSchema:()=>[{key:"providers",label:"供应商",type:"provider-list",secret:true},{key:"defaultProvider",label:"默认供应商",type:"string"},{key:"prompts",label:"提示词",type:"prompt-map"},{key:"timeoutMs",label:"超时（毫秒）",type:"number",min:10_000,max:300_000},{key:"collapse",label:"折叠输出",type:"boolean"}],getValues:()=>store(c).read(),async setValues(patch){await store(c).update(value=>normalize({...value,...patch,legacyImported:true}));}}),async setup(c){await migrate(c);}});}
