import {definePlugin, type MessageEnvelope, type PluginContext} from "telebox/sdk";

type Entry={name:string;key:string;baseUrl:string;addedAt:number};
type State={schemaVersion:1;entries:Entry[];legacyImported:boolean;[key:string]:unknown};
const defaults:State={schemaVersion:1,entries:[],legacyImported:false};
const store=(c:PluginContext)=>c.storage.json<State>("keys-v2.json",defaults);
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[x]!);
const mask=(s:string)=>s.length<12?"***":`${s.slice(0,4)}…${s.slice(-4)}`;
function api(base:string,path:string){const u=new URL(base.includes("://")?base:`https://${base}`);if(!/^https?:$/.test(u.protocol)||u.username||u.password)throw new Error("API 地址无效");u.pathname=`${u.pathname.replace(/\/+$/,"")}${path}`;u.hash="";return u;}
async function bounded(r:Response,s:AbortSignal){const reader=r.body?.getReader();if(!reader)return"";const chunks:Buffer[]=[];let total=0;try{for(;;){s.throwIfAborted();const x=await reader.read();if(x.done)break;total+=x.value.length;if(total>1024*1024)throw new Error("API 响应过大");chunks.push(Buffer.from(x.value));}return Buffer.concat(chunks).toString("utf8");}finally{reader.releaseLock();}}
async function json(c:PluginContext,url:URL,init:RequestInit){return c.http.withResponse(url,init,async(r,s)=>{const text=await bounded(r,s);let data:unknown;try{data=JSON.parse(text);}catch{throw new Error("API 返回的不是 JSON");}if(!r.ok)throw new Error(`HTTP ${r.status}`);return data;},{timeoutMs:20_000,redirects:{allowedHosts:[url.hostname],maxRedirects:2}});}
function models(data:any):string[]{const rows=Array.isArray(data?.data)?data.data:Array.isArray(data?.models)?data.models:[];return rows.map((x:any)=>String(x?.id??x?.name??"")).filter(Boolean).slice(0,100);}
function text(data:any){return String(data?.choices?.[0]?.message?.content??data?.candidates?.[0]?.content?.parts?.[0]?.text??"");}
async function resolve(c:PluginContext,input:string,base?:string){const state=await store(c).read();const saved=state.entries.find(x=>x.name===input);const key=saved?.key??input;const baseUrl=base??saved?.baseUrl;if(!key||!baseUrl)throw new Error("请提供已保存名称，或同时提供 URL 与 Key");return{key,baseUrl};}
async function migrate(c:PluginContext){const current=await store(c).read();if(current.legacyImported)return;let entries:Entry[]=[];try{const legacy=JSON.parse(await (await import("node:fs/promises")).readFile(c.files.dataPath("keys.json"),"utf8"));if(Array.isArray(legacy))entries=legacy.flatMap((x:any)=>typeof x?.name==="string"&&typeof x?.key==="string"&&typeof x?.baseUrl==="string"?[{name:x.name,key:x.key,baseUrl:x.baseUrl,addedAt:Number(x.addedAt)||Date.now()}]:[]);}catch{}await store(c).update(v=>({...v,schemaVersion:1,entries:v.entries.length?v.entries:entries,legacyImported:true}));}
async function command(message:MessageEnvelope,args:readonly string[],prefix:string,c:PluginContext){const sub=args[0]?.toLowerCase()??"";try{
  if(!sub||sub==="help"){await c.telegram.edit(message,`<b>API 检测</b>\n<code>${esc(prefix)}checkapi save 名称 URL Key</code>\n<code>${esc(prefix)}checkapi list|del 名称|models 名称|ask 名称 问题|check 名称</code>`,{parseMode:"html"});return;}
  if(sub==="list"){const s=await store(c).read();await c.telegram.edit(message,s.entries.length?s.entries.map(x=>`<b>${esc(x.name)}</b> ${esc(mask(x.key))} ${esc(new URL(x.baseUrl).hostname)}`).join("\n"):"尚未保存 API",{parseMode:"html"});return;}
  if(sub==="save"&&!message.saved)throw new Error("密钥管理仅限收藏夹");
  if(sub==="save"){const[name,baseUrl,key]=args.slice(1);if(!name||!baseUrl||!key)throw new Error("用法：checkapi save 名称 URL Key");api(baseUrl,"/models");let replaced=false;await store(c).update(v=>{const entries=v.entries.filter(x=>x.name!==name);replaced=entries.length!==v.entries.length;return{...v,entries:[...entries,{name,key,baseUrl:baseUrl.replace(/\/+$/,"")!,addedAt:Date.now()}]};});try{const target=api(baseUrl,"/models");await json(c,target,{headers:{authorization:`Bearer ${key}`}});}catch{await c.telegram.edit(message,`API ${replaced?"配置已更新":"已保存"}，验证失败；请检查地址或密钥。`);return;}await c.telegram.edit(message,`API ${replaced?"配置已更新":"已保存"}并验证成功。`);return;}
  if(sub==="del"){const name=args[1];if(!name)throw new Error("请提供名称");let removed=false;await store(c).update(v=>({...v,entries:v.entries.filter(x=>{if(x.name===name){removed=true;return false;}return true;})}));await c.telegram.edit(message,removed?"API 配置已删除。":"未找到该配置。");return;}
  const inline=args[1]?.includes("://")&&args[2]?{base:args[1],key:args[2],offset:3}:undefined;const got=await resolve(c,inline?.key??args[1]??sub,inline?.base);
  if(sub==="models"||sub==="check"){const target=api(got.baseUrl,"/models");const data=await json(c,target,{headers:{authorization:`Bearer ${got.key}`}});const list=models(data);if(!list.length)throw new Error("API 响应缺少模型列表");await c.telegram.edit(message,sub==="check"?`✅ API 有效，共 ${list.length} 个模型。`:`<b>模型列表</b>\n${esc(list.join("\n").slice(0,3500))}`,{parseMode:"html"});return;}
  if(sub==="ask"){const prompt=args.slice(inline?.offset??2).join(" ")||"say hello";const target=api(got.baseUrl,"/chat/completions");const data=await json(c,target,{method:"POST",headers:{authorization:`Bearer ${got.key}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-4o-mini",messages:[{role:"user",content:prompt}],max_tokens:100})});const output=text(data);if(!output)throw new Error("API 响应缺少消息内容");await c.telegram.edit(message,esc(output),{parseMode:"html"});return;}
  throw new Error("未知子命令");
}catch(e){if(!c.signal.aborted)await c.telegram.edit(message,`❌ ${esc(e instanceof Error?e.message:"请求失败")}`,{parseMode:"html"});}}
export default function createCheckapi(){return definePlugin({apiVersion:1,id:"checkapi",description:"验证 OpenAI 兼容 API、模型与对话",commands:{checkapi:{description:"管理并检测 API",async handle(i,c){await command(i.message,i.args,i.prefix,c);}}},settings:c=>({id:"checkapi",title:"API 检查",description:"保存的 API 连接（密钥字段受秘密设置保护）",category:"插件配置",icon:"🔑",getSchema:()=>[{key:"entries",label:"API 连接",type:"provider-list",secret:true}],getValues:async()=>({entries:(await store(c).read()).entries}),async setValues(p){if(!Array.isArray(p.entries))throw new Error("invalid entries");const entries=p.entries.flatMap((x:any)=>typeof x?.name==="string"&&typeof x?.key==="string"&&typeof x?.baseUrl==="string"?[{name:x.name,key:x.key,baseUrl:x.baseUrl,addedAt:Number(x.addedAt)||Date.now()}]:[]);for(const x of entries)api(x.baseUrl,"/models");await store(c).update(v=>({...v,entries}));}}),setup:migrate});}
