import {definePlugin,type MessageEnvelope,type PluginContext} from "telebox/sdk";
type Config={schemaVersion:1;url:string;legacyImported:boolean;[key:string]:unknown};
const defaults:Config={schemaVersion:1,url:"",legacyImported:false};
const store=(c:PluginContext)=>c.storage.json<Config>("config-v2.json",defaults);
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[x]!);
const number=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:0;
function base(input:string){const u=new URL(input.includes("://")?input:`https://${input}`);if(!/^https?:$/.test(u.protocol)||u.username||u.password)throw new Error("Komari 地址无效");u.pathname=u.pathname.replace(/\/+$/,"");u.search="";u.hash="";return u;}
async function get(c:PluginContext,root:URL,endpoint:string){const u=new URL(root);u.pathname=`${u.pathname}${endpoint}`;return c.http.withResponse(u,{headers:{accept:"application/json","user-agent":"MiBot-Komari/2"}},async(r,s)=>{const reader=r.body?.getReader();if(!reader)throw new Error("Komari 返回空响应");const chunks:Buffer[]=[];let total=0;try{for(;;){s.throwIfAborted();const x=await reader.read();if(x.done)break;total+=x.value.length;if(total>2*1024*1024)throw new Error("Komari 响应过大");chunks.push(Buffer.from(x.value));}}finally{reader.releaseLock();}let data:any;try{data=JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new Error("Komari 返回无效 JSON");}if(!r.ok)throw new Error(`HTTP ${r.status}`);if(data?.status!=="success"||data.data===undefined)throw new Error("Komari 响应结构异常");return data.data;},{timeoutMs:10_000,redirects:{allowedHosts:[u.hostname],maxRedirects:2}});}
function bytes(v:number){if(v<=0)return"0 B";const units=["B","KB","MB","GB","TB","PB"],i=Math.min(units.length-1,Math.floor(Math.log(v)/Math.log(1024)));return`${(v/1024**i).toFixed(i?2:0)} ${units[i]}`;}
async function status(c:PluginContext,root:URL){const[p,v,n]=await Promise.all([get(c,root,"/api/public"),get(c,root,"/api/version"),get(c,root,"/api/nodes")]);if(!Array.isArray(n))throw new Error("节点列表结构异常");const totals=n.reduce((a:any,x:any)=>({cpu:a.cpu+number(x?.cpu_cores),mem:a.mem+number(x?.mem_total),swap:a.swap+number(x?.swap_total),disk:a.disk+number(x?.disk_total)}),{cpu:0,mem:0,swap:0,disk:0});return`<b>Komari 服务信息</b>\n站点：<code>${esc(p?.sitename??"未知")}</code>\n版本：<code>${esc(`${v?.version??"?"}-${v?.hash??"?"}`)}</code>\n节点：${n.length}\nCPU：${totals.cpu} 核\n内存：${bytes(totals.mem)}\n交换：${bytes(totals.swap)}\n硬盘：${bytes(totals.disk)}`;}
async function total(c:PluginContext,root:URL){const n=await get(c,root,"/api/nodes");if(!Array.isArray(n))throw new Error("节点列表结构异常");const rows=await Promise.all(n.slice(0,100).map(async(x:any)=>{try{const r=await get(c,root,`/api/recent/${encodeURIComponent(String(x.uuid??""))}`);return{x,r:Array.isArray(r)?r[0]:undefined};}catch{return{x,r:undefined};}}));const online=rows.filter(x=>x.r);return`<b>Komari 节点总览</b> (${online.length}/${rows.length} 在线)\n\n${rows.map(({x,r})=>`${r?"🟢":"🔴"} <b>${esc(x?.name??x?.uuid??"未知")}</b>${r?`\nCPU ${number(r.cpu?.usage).toFixed(1)}% · 内存 ${bytes(number(r.ram?.used))}/${bytes(number(r.ram?.total))}\n网络 ↓${bytes(number(r.network?.down))}/s ↑${bytes(number(r.network?.up))}/s`:""}`).join("\n\n").slice(0,3900)}`;}
async function show(c:PluginContext,root:URL,name:string){const n=await get(c,root,"/api/nodes");if(!Array.isArray(n))throw new Error("节点列表结构异常");const node=n.find((x:any)=>String(x?.name)===name);if(!node)throw new Error("未找到节点");const r=await get(c,root,`/api/recent/${encodeURIComponent(String(node.uuid??""))}`),live=Array.isArray(r)?r[0]:undefined;if(!live)throw new Error("节点无实时数据");return`<b>${esc(name)}</b>\nCPU：${number(live.cpu?.usage).toFixed(2)}%\n内存：${bytes(number(live.ram?.used))}/${bytes(number(live.ram?.total))}\n硬盘：${bytes(number(live.disk?.used))}/${bytes(number(live.disk?.total))}\n流量：↓${bytes(number(live.network?.totalDown))} ↑${bytes(number(live.network?.totalUp))}`;}
async function migrate(c:PluginContext){const current=await store(c).read();if(current.legacyImported)return;let url="";try{const db=c.storage.sqlite("komari_config.db",{readonly:true});url=await db.read(x=>String((x.prepare("SELECT value FROM config WHERE key = ?").get("komari_url") as any)?.value??""));}catch{}await store(c).update(v=>({...v,url:v.url||url,legacyImported:true}));}
async function command(m:MessageEnvelope,args:readonly string[],c:PluginContext){try{if(args[0]==="_set_url"){const url=args[1];if(!url)throw new Error("请提供 Komari 地址");base(url);await store(c).update(v=>({...v,url:url.replace(/\/+$/,"")}));await c.telegram.edit(m,"Komari 地址已保存。");return;}const config=await store(c).read();if(!config.url)throw new Error("请先使用 komari _set_url <URL> 配置");const root=base(config.url),sub=args[0]??"status";await c.telegram.edit(m,"正在获取 Komari 数据…");const out=sub==="status"?await status(c,root):sub==="total"?await total(c,root):sub==="show"&&args.slice(1).length?await show(c,root,args.slice(1).join(" ")):(()=>{throw new Error("未知子命令")})();await c.telegram.edit(m,out,{parseMode:"html"});}catch(e){if(!c.signal.aborted)await c.telegram.edit(m,`❌ ${esc(e instanceof Error?e.message:"Komari 请求失败")}`,{parseMode:"html"});}}
export default function createKomari(){return definePlugin({apiVersion:1,id:"komari",description:"查询 Komari 服务与节点状态",commands:{komari:{description:"查询或配置 Komari",async handle(i,c){await command(i.message,i.args,c);}}},settings:c=>({id:"komari",title:"Komari",category:"插件配置",icon:"📡",getSchema:()=>[{key:"url",label:"服务地址",type:"string"}],getValues:async()=>({url:(await store(c).read()).url}),async setValues(p){if(typeof p.url!=="string")throw new Error("invalid URL");const url=p.url;base(url);await store(c).update(v=>({...v,url:url.replace(/\/+$/,"")}));}}),setup:migrate});}
