import {definePlugin, type PluginContext} from "telebox/sdk";

type Repo={tag:string;repo:string;url:string;addedAt:string};
type Turn={q:string;a:string;at:string};
type Chat={currentTag:string;repos:Record<string,Repo>;contextEnabled:boolean;turns:Record<string,Turn[]>};
type Data={schemaVersion:number;chats:Record<string,Chat>;legacyImported?:boolean};
const HOST="mcp.deepwiki.com", MAX_TURNS=50, MAX_QUESTION=48_000;
const defaults:Data={schemaVersion:1,chats:{}};
const esc=(s:string)=>s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c]!);
const store=(ctx:PluginContext)=>ctx.storage.json<Data>("data.json",defaults);
const key=(m:{chatId:string;topicId?:number})=>m.topicId?`${m.chatId}:topic:${m.topicId}`:m.chatId;
const empty=():Chat=>({currentTag:"",repos:{},contextEnabled:false,turns:{}});
const help=(p:string)=>`<b>📚 DeepWiki</b>\n<code>${esc(p)}deepwiki add tag https://github.com/owner/repo</code>\n<code>${esc(p)}deepwiki lst</code> · <code>use tag</code> · <code>del tag</code>\n<code>${esc(p)}deepwiki ctx on|off|del [tag|all]</code>\n<code>${esc(p)}deepwiki [tag] 问题</code>`;
function repoUrl(raw:string){try{const u=new URL(raw);if(!["github.com","deepwiki.com"].includes(u.hostname.toLowerCase()))return;let p=u.pathname.split("/").filter(Boolean);if(u.hostname==="deepwiki.com"&&p[0]==="browse"&&p[1]==="github.com")p=p.slice(2);const owner=p[0],name=p[1]?.replace(/\.git$/i,"");if(!owner||!name||!/^[\w.-]+$/.test(owner)||!/^[\w.-]+$/.test(name))return;return{repo:`${owner}/${name}`,url:`https://github.com/${owner}/${name}`};}catch{return;}}
function responseValue(text:string):any{const lines=text.split(/\r?\n/).filter(x=>x.startsWith("data:"));const raw=lines.length?lines.at(-1)!.slice(5).trim():text.trim();return JSON.parse(raw);}
async function boundedText(response:Response,signal:AbortSignal){const reader=response.body?.getReader();if(!reader)return"";const decoder=new TextDecoder();const chunks:string[]=[];let total=0;try{while(true){signal.throwIfAborted();const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>2*1024*1024)throw new Error("large");chunks.push(decoder.decode(part.value,{stream:true}));}chunks.push(decoder.decode());return chunks.join("");}finally{reader.releaseLock();}}
async function rpc(ctx:PluginContext,body:unknown,session?:string){return ctx.http.withResponse(`https://${HOST}/mcp`,{method:"POST",headers:{accept:"application/json, text/event-stream","content-type":"application/json",...(session?{"mcp-session-id":session}:{})},body:JSON.stringify(body)},async (response,signal)=>{if(!response.ok)throw new Error("status");const sessionId=response.headers.get("mcp-session-id")??session;const value=response.status===202?undefined:responseValue(await boundedText(response,signal));return{session:sessionId,value};},{timeoutMs:30000,redirects:{allowedHosts:[HOST],maxRedirects:1}});}
async function ask(ctx:PluginContext,repo:string,question:string){const init=await rpc(ctx,{jsonrpc:"2.0",id:1,method:"initialize",params:{protocolVersion:"2025-03-26",capabilities:{},clientInfo:{name:"mibot-deepwiki",version:"2"}}});if(!init.session)throw new Error("session");await rpc(ctx,{jsonrpc:"2.0",method:"notifications/initialized"},init.session);const result=await rpc(ctx,{jsonrpc:"2.0",id:2,method:"tools/call",params:{name:"ask_question",arguments:{repoName:repo,question}}},init.session);const content=result.value?.result?.content;if(!Array.isArray(content))throw new Error("content");const text=content.filter((x:any)=>x?.type==="text"&&typeof x.text==="string").map((x:any)=>x.text).join("\n").split("Wiki pages you might want to explore:")[0]!.trim();if(!text)throw new Error("empty");return text;}
function render(repo:string,q:string,a:string){const first=`<b>项目:</b> <code>${esc(repo)}</code>\nQ:\n<blockquote expandable>${esc(q.slice(0,1200))}</blockquote>\nA:\n`;const chars=Array.from(a),pages:string[]=[];for(let pos=0;pos<chars.length;pos+=2400){const body=esc(chars.slice(pos,pos+2400).join(""));pages.push(`${pages.length?`<b>项目:</b> <code>${esc(repo)}</code> · 续\n`:first}<blockquote expandable>${body}</blockquote>`);}return pages.length?pages:[`${first}<blockquote expandable>（空）</blockquote>`];}
export default function createDeepWiki(){return definePlugin({apiVersion:1,id:"deepwiki",description:"基于 DeepWiki 查询 GitHub 项目文档",async setup(ctx){const db=store(ctx);const current=await db.read();if(current.legacyImported)return;const legacyMain=await ctx.storage.json<any>("config.json",{}).read();const legacyContext=await ctx.storage.json<any>("context.json",{}).read();await db.update(data=>{if(data.legacyImported)return data;const chats={...((legacyMain?.chats&&typeof legacyMain.chats==="object")?legacyMain.chats:{}),...data.chats};for(const [chatId,value] of Object.entries((legacyContext?.chats&&typeof legacyContext.chats==="object")?legacyContext.chats:{})){const old=value as any;const target=chats[chatId]??empty();chats[chatId]={...target,contextEnabled:!!old?.contextEnabled,turns:old?.contextTurns&&typeof old.contextTurns==="object"?old.contextTurns:target.turns};}return{schemaVersion:1,chats,legacyImported:true};});},commands:{deepwiki:{description:"管理项目并向 DeepWiki 提问",async handle(invocation,ctx){const chatKey=key(invocation.message);const data=await store(ctx).read();const state=data.chats[chatKey]??empty();const args=[...invocation.args];const sub=(args[0]??"").toLowerCase();const save=async()=>{await store(ctx).update(d=>({...d,schemaVersion:1,chats:{...d.chats,[chatKey]:state}}));};try{
if(!sub||sub==="help"||sub==="h"){await ctx.telegram.edit(invocation.message,help(invocation.prefix),{parseMode:"html"});return;}
if(sub==="add"){const tag=args[1]?.trim(),parsed=repoUrl(args[2]??"");if(!tag||!/^[\w.-]{1,40}$/.test(tag)||!parsed)throw new Error("用法：deepwiki add <tag> <GitHub URL>");state.repos[tag]={tag,...parsed,addedAt:new Date().toISOString()};state.currentTag=tag;await save();await ctx.telegram.edit(invocation.message,`✅ 已添加 <code>${esc(tag)}</code>：<code>${esc(parsed.repo)}</code>`,{parseMode:"html"});return;}
if(sub==="lst"){const rows=Object.values(state.repos).sort((a,b)=>a.tag.localeCompare(b.tag)).map(x=>`${x.tag===state.currentTag?"✅":"•"} <code>${esc(x.tag)}</code> — ${esc(x.repo)}`);await ctx.telegram.edit(invocation.message,`<b>项目列表</b>\n${rows.join("\n")||"暂无项目"}`,{parseMode:"html"});return;}
if(sub==="use"){const tag=args[1]??"";if(!state.repos[tag])throw new Error("项目不存在");state.currentTag=tag;await save();await ctx.telegram.edit(invocation.message,`✅ 已切换到 <code>${esc(tag)}</code>`,{parseMode:"html"});return;}
if(sub==="del"){const tag=args[1]??"";if(!state.repos[tag])throw new Error("项目不存在");delete state.repos[tag];delete state.turns[tag];if(state.currentTag===tag)state.currentTag="";await save();await ctx.telegram.edit(invocation.message,`✅ 已删除 <code>${esc(tag)}</code>`,{parseMode:"html"});return;}
if(sub==="ctx"){const action=(args[1]??"").toLowerCase();if(action==="on"||action==="off"){state.contextEnabled=action==="on";await save();await ctx.telegram.edit(invocation.message,`✅ 上下文已${state.contextEnabled?"开启":"关闭"}`);return;}if(action==="del"){const tag=args[2]??state.currentTag;if(args[2]==="all")state.turns={};else if(tag)delete state.turns[tag];await save();await ctx.telegram.edit(invocation.message,"✅ 上下文已清空");return;}await ctx.telegram.edit(invocation.message,`上下文：${state.contextEnabled?"开":"关"}；当前项目：${state.currentTag||"未设置"}`);return;}
let tag=state.currentTag,q=args.join(" ").trim();if(state.repos[args[0]!]&&args.length>1){tag=args.shift()!;q=args.join(" ").trim();}const reply=invocation.message.replyToId!==undefined?await ctx.telegram.getReply(invocation.message):undefined;if(reply?.text)q=`${reply.text}\n\n${q}`.trim();if(!tag||!state.repos[tag])throw new Error("尚未设置可用项目");if(!q)throw new Error("请输入问题内容");const turns=state.contextEnabled?(state.turns[tag]??[]):[];const context=turns.map((t,i)=>`Q${i+1}: ${t.q}\nA${i+1}: ${t.a}`).join("\n\n");const final=(context?`${context}\n\n当前问题: ${q}`:q).slice(-MAX_QUESTION);await ctx.telegram.edit(invocation.message,"💬 <b>DeepWiki 正在处理</b>",{parseMode:"html"});const answer=await ask(ctx,state.repos[tag]!.repo,final);if(state.contextEnabled){state.turns[tag]=[...turns,{q,a:answer.slice(0,12000),at:new Date().toISOString()}].slice(-MAX_TURNS);await save();}const output=render(state.repos[tag]!.repo,q,answer.slice(0,MAX_QUESTION));for(let i=0;i<output.length;i++){if(i===0)await ctx.telegram.edit(invocation.message,output[i]!,{parseMode:"html",linkPreview:false});else await ctx.telegram.reply(invocation.message,output[i]!,{parseMode:"html",linkPreview:false});}
}catch{if(!ctx.signal.aborted)await ctx.telegram.edit(invocation.message,"❌ DeepWiki 操作失败，请检查参数或稍后重试");}}}}});}
