'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const core=path.resolve(__dirname,'../../TeleBox-Core'),{buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs')),{PluginHost}=require(path.join(core,'dist/v2/host.js'));
function plugin(){const {artifactDir}=buildPlugin({id:'fadian',packageRoot:path.resolve(__dirname,'../fadian'),entry:'v2.ts'}),entry=path.join(artifactDir,'index.cjs');delete require.cache[require.resolve(entry)];return require(entry).default();}
async function fixture(t,responder=()=>Response.json(['语录：<name><name1><name2>']),failEdit,options={}){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'mibot-fadian-compat-'))),edits=[],replies=[],requests=[];let reply;const host=new PluginHost({storageRoot:root,prefixes:options.prefixes,aliases:options.aliases,logger:{info(){},error(){}},http:{fetch:async url=>{requests.push(new URL(url));return responder(new URL(url));}},telegram:{async edit(_m,text,sendOptions){if(failEdit){const failure=failEdit(text);if(failure)throw failure;}edits.push({text,options:sendOptions});},async reply(_m,text,sendOptions){replies.push({text,options:sendOptions});if(options.onReply)await options.onReply(text);},async invoke(){assert.fail('invoke');},async getReply(){return reply;},async withClient(){assert.fail('native');}}});await host.load(plugin());t.after(async()=>{await host.shutdown(2000);await fs.rm(root,{recursive:true,force:true});});return{host,edits,replies,requests,setReply:v=>{reply=v;},run:(text,message={})=>host.dispatchPrimary({id:1,chatId:'1',senderId:'1',outgoing:true,text,...message})};}

test('fadian keeps original help and validation matrix',async t=>{const f=await fixture(t);await f.run('.fadian');assert.match(f.edits.at(-1).text,/\.fadian fd 张三/);await f.run('.fadian help fd');assert.match(f.edits.at(-1).text,/心理语录命令帮助/);await f.run('.fadian tg h');assert.match(f.edits.at(-1).text,/TG语录命令帮助/);await f.run('.fadian fd');assert.match(f.edits.at(-1).text,/参数不足/);await f.run('.fadian cp only');assert.match(f.edits.at(-1).text,/第二行写第一个名字/);await f.run('.fadian unknown<&');assert.match(f.edits.at(-1).text,/unknown&lt;&amp;/);assert.equal(f.requests.length,0);});

test('fadian keeps generators, reply names, progress, per-kind cache and clear',async t=>{const f=await fixture(t,url=>Response.json(url.pathname.endsWith('cp.json')?['<name1> + <name2>']:url.pathname.endsWith('psycho.json')?['爱你，<name>']:['plain']));f.setReply({raw:{sender:{firstName:'Alice',lastName:'<Smith>'}}});await f.run('.fadian fd');assert.equal(f.edits.at(-2).text,'🔄 生成心理语录中...');assert.equal(f.edits.at(-1).text,'爱你，Alice &lt;Smith&gt;');await f.run('.fadian fd explicit');assert.equal(f.requests.filter(x=>x.pathname.endsWith('psycho.json')).length,1);await f.run('.fadian cp\n甲 方\n乙 方');assert.equal(f.edits.at(-1).text,'甲 方 + 乙 方');for(const kind of ['tg','kfc','wyy'])await f.run(`.fadian ${kind}`);assert.deepEqual(f.requests.map(x=>path.basename(x.pathname)).sort(),['cp.json','kfc.json','psycho.json','tg.json','wyy.json']);await f.run('.fadian clear');assert.deepEqual(f.edits.slice(-2).map(x=>x.text),['🔄 清理缓存中...','🧹 缓存已清理，下次使用时将重新下载配置']);await f.run('.fadian tg');assert.equal(f.requests.filter(x=>x.pathname.endsWith('tg.json')).length,2);});

test('fadian hides HTTP failure details behind fixed safe feedback',async t=>{const f=await fixture(t,()=>{throw new Error('authorization token: secret');});await f.run('.fadian tg');assert.match(f.edits.at(-1).text,/请稍后重试/);assert.doesNotMatch(f.edits.at(-1).text,/secret|authorization token/);});

test('fadian preserves FLOOD_WAIT and MESSAGE_TOO_LONG feedback',async t=>{for(const [failure,expected] of [[Object.assign(new Error('private'),{errorMessage:'FLOOD_WAIT_17'}),/等待 17 秒/],[Object.assign(new Error('private'),{errorMessage:'MESSAGE_TOO_LONG'}),/消息过长/]]){let once=true;const f=await fixture(t,()=>Response.json(['plain']),text=>{if(text==='plain'&&once){once=false;return failure;}});await f.run('.fadian tg');assert.match(f.edits.at(-1).text,expected);assert.doesNotMatch(f.edits.at(-1).text,/private|FLOOD_WAIT|MESSAGE_TOO_LONG/);}});

test('fadian unload aborts HTTP without false failure feedback',async t=>{let started;const ready=new Promise(resolve=>{started=resolve;}),f=await fixture(t,()=>new Response(new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode('['));started();}})));const running=f.run('.fadian tg');await ready;assert.equal((await f.host.unload('fadian',2000)).completed,true);await running;assert.equal(f.edits.filter(x=>/插件执行失败/.test(x.text)).length,0);});

test('fadian preserves raw multiline names through a multiword alias and non-default prefix',async t=>{const f=await fixture(t,()=>Response.json(['<name1> ❤️ <name2>']),undefined,{prefixes:['!'],aliases:{'给我发癫':'fadian cp'}});await f.run('!给我发癫 ignored normalized text',{raw:{message:'!给我发癫\n张 三\n李 四'}});assert.equal(f.edits.at(-1).text,'张 三 ❤️ 李 四');});

test('fadian paginates expanded escaped output and reports a later interruption without replacing content',async t=>{const body='开头 & 😀 <name> 结尾';const f=await fixture(t,()=>Response.json([body]));await f.run(`.fadian fd ${'<&😀'.repeat(1400)}`);const pages=[f.edits.at(-1),...f.replies].map(x=>x.text);assert.ok(pages.length>1);assert.ok(pages.every(page=>page.length<=4096&&page.isWellFormed()));assert.match(pages[0],/\n1\/\d+ 页$/);assert.match(pages.join('\n'),/开头 &amp; 😀/);let failed=false;const partial=await fixture(t,()=>Response.json([body]),undefined,{onReply(){if(!failed){failed=true;throw new Error('reply failed');}}});await partial.run(`.fadian fd ${'<&😀'.repeat(1400)}`);assert.doesNotMatch(partial.edits.at(-1).text,/插件执行失败/);assert.match(partial.replies.at(-1).text,/已发送 1\/\d+ 页，后续页发送中断/);});

test('fadian clear fences an older in-flight download from cache and publication',async t=>{let release;const delayed=new Promise(resolve=>{release=resolve;});let calls=0;const f=await fixture(t,async()=>{calls++;if(calls===1){await delayed;return Response.json(['old']);}return Response.json(['new']);});const old=f.run('.fadian tg',{chatId:'old',id:1});while(calls===0)await new Promise(resolve=>setTimeout(resolve,1));await f.run('.fadian clear',{chatId:'clear',id:2});release();await old;assert.doesNotMatch(f.edits.map(x=>x.text).join('\n'),/^old$/m);await f.run('.fadian tg',{chatId:'new',id:3});assert.equal(f.edits.at(-1).text,'new');assert.equal(calls,2);});
