'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const core=path.resolve(__dirname,'../../TeleBox-Core'),{buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs')),{PluginHost}=require(path.join(core,'dist/v2/host.js'));
function plugin(id){const {artifactDir}=buildPlugin({id,packageRoot:path.resolve(__dirname,`../${id}`),entry:'v2.ts'});delete require.cache[require.resolve(path.join(artifactDir,'index.cjs'))];return require(path.join(artifactDir,'index.cjs')).default();}
async function fixture(t,id,options={}){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),`mibot-${id}-`))),edits=[],sent=[],requests=[];if(options.setupRoot)await options.setupRoot(root);let reply=options.reply;const client={...options.client,async sendFile(peer,value){sent.push({peer,value});},async sendMessage(peer,value){sent.push({peer,value});}};const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},http:{fetch:async(url,init)=>{requests.push({url:new URL(url),init});return options.fetch?options.fetch(url,init):new Response('missing',{status:500});}},telegram:{async edit(message,text,messageOptions){edits.push({message,text,options:messageOptions});},async reply(message,text,messageOptions){edits.push({message,text,options:messageOptions});},async invoke(request){return client.invoke?.(request);},async getReply(){return reply;},async withClient(operation,signal){return operation(client,signal);}}});await host.load(plugin(id));t.after(async()=>{assert.equal((await host.shutdown(2000)).completed,true);await fs.rm(root,{recursive:true,force:true});});return{root,host,edits,sent,requests,setReply:v=>reply=v,run:(text,message={})=>host.dispatchPrimary({id:1,chatId:'-10010',senderId:'42',outgoing:true,text,...message})};}

test('banana protects the key and performs a bounded Gemini edit',async t=>{const input=Buffer.from('image'),output=Buffer.from('generated');const f=await fixture(t,'banana',{reply:{id:9,raw:{media:{photo:{}}}},client:{async *iterDownload(){yield input;}},fetch:async()=>Response.json({candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:output.toString('base64')}}]}}]})});await f.run('.banana key secret');assert.match(f.edits.at(-1).text,/仅允许在收藏夹/);await f.run('.banana key secret',{saved:true});await f.run('.banana recolor',{replyToId:9,raw:{peerId:{},async delete(){}}});assert.equal(f.requests.length,1);assert.equal(f.requests[0].url.hostname,'generativelanguage.googleapis.com');assert.equal(JSON.parse(f.requests[0].init.body).contents[0].parts[1].inline_data.data,input.toString('base64'));assert.equal(f.sent.length,1);assert.equal(f.sent[0].value.file.size,output.length);const settings=await f.host.readSettings('banana');assert.equal(settings.secretSet.apiKey,true);assert.equal(settings.values.apiKey,undefined);});

test('banana migration is idempotent and redirects cannot leave the provider host',async t=>{const input=Buffer.from('image');const f=await fixture(t,'banana',{setupRoot:async root=>{const dir=path.join(root,'banana');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'config.json'),JSON.stringify({apiKey:'legacy-key',maxBytes:2097152}));},reply:{id:9,raw:{media:{photo:{}}}},client:{async *iterDownload(){yield input;}},fetch:async()=>new Response('',{status:302,headers:{location:'https://evil.example/image'}})});await f.run('.banana config');assert.match(f.edits.at(-1).text,/已配置/);await f.run('.banana edit',{replyToId:9,raw:{peerId:{}}});assert.equal(f.requests.length,1);assert.match(f.edits.at(-1).text,/失败/);assert.doesNotMatch(f.edits.map(x=>x.text).join('\n'),/legacy-key/);assert.equal((await f.host.unload('banana')).completed,true);await f.host.load(plugin('banana'));await f.run('.banana config');assert.match(f.edits.at(-1).text,/2MB/);});

test('codex_image parses SSE, sends the image, and redacts credentials',async t=>{const output=Buffer.from('png');const sse=`data: ${JSON.stringify({type:'response.created',response:{id:'resp_1',status:'in_progress'}})}\n\ndata: ${JSON.stringify({type:'response.image_generation_call.partial_image',partial_image_b64:output.toString('base64'),revised_prompt:'safe'})}\n\ndata: [DONE]\n\n`;const f=await fixture(t,'codex_image',{fetch:async()=>new Response(sse,{headers:{'content-type':'text/event-stream'}}),client:{}});await f.run('.cximg token top-secret');assert.match(f.edits.at(-1).text,/仅允许在收藏夹/);await f.run('.cximg token top-secret',{saved:true});await f.run('.cximg draw cat',{raw:{peerId:{},async delete(){}}});assert.equal(f.sent[0].value.file.size,output.length);assert.equal(f.requests[0].init.headers.Authorization,'Bearer top-secret');assert.doesNotMatch(f.edits.map(x=>x.text).join('\n'),/top-secret/);const settings=await f.host.readSettings('codex_image');assert.equal(settings.secretSet.accessToken,true);assert.equal(settings.values.accessToken,undefined);});

test('codex_image cancellation drains an in-flight provider request',async t=>{let started;const ready=new Promise(resolve=>{started=resolve;});const f=await fixture(t,'codex_image',{fetch:async(_url,init)=>{started();return new Promise((_resolve,reject)=>init.signal.addEventListener('abort',()=>reject(init.signal.reason),{once:true}));},client:{}});await f.run('.cximg token token',{saved:true});const running=f.run('.cximg long task',{raw:{peerId:{}}});await ready;assert.equal((await f.host.unload('codex_image',2000)).completed,true);await running;});

test('cy migrates schedule state and generates a bounded word cloud',async t=>{const f=await fixture(t,'cy',{client:{async *iterMessages(){for(let i=0;i<8;i++)yield{text:'迁移测试 迁移测试 telegram plugin'};}}});await f.run('.cy target here');await f.run('.cy time 09:00 100');await f.run('.cy on');assert.match(f.edits.at(-1).text,/on/);await f.run('.cy 100',{raw:{async delete(){}}});assert.equal(f.sent.length,1);assert.equal(f.sent[0].value.file.name,'cy-wordcloud.png');assert.ok(f.sent[0].value.file.size>100);});

test('fbi persists consecutive public-group messages across immediate reload and supports watch completion',async t=>{const group={id:10,username:'publicgroup',title:'Public',className:'Channel'},user={id:42,username:'suspect',firstName:'Target'};const f=await fixture(t,'fbi',{client:{async getEntity(value){return String(value)==='42'?user:group;}}});await f.host.dispatchListeners({id:4,chatId:'-10010',chatType:'supergroup',senderId:'42',outgoing:false,text:'hello trace',raw:{date:10000000000,peerId:{}}});await f.host.dispatchListeners({id:5,chatId:'-10010',chatType:'supergroup',senderId:'42',outgoing:false,text:'continued trace',raw:{date:10000000001,peerId:{}}});assert.equal((await f.host.unload('fbi',2000)).completed,true);const saved=JSON.parse(await fs.readFile(path.join(f.root,'fbi','cache.json'),'utf8'));assert.deepEqual(saved.cache['-10010'].msgs.map(message=>message.text),['continued trace','hello trace']);await f.host.load(plugin('fbi'));await f.run('.fbi det 42');assert.match(f.edits.at(-1).text,/continued trace/);await f.run('.fbi sur 42');await f.host.dispatchListeners({id:6,chatId:'-10010',chatType:'supergroup',senderId:'42',outgoing:false,text:'next move',raw:{date:10000000002,peerId:{}}});assert.equal(f.sent.length,2);assert.match(f.sent[0].value.message,/next move/);});

test('all generation/tracking artifacts load, unload, and reload in a real host',async t=>{for(const id of ['banana','codex_image','cy','fbi']){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),`mibot-cycle-${id}-`)));const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},http:{fetch:async()=>new Response('',{status:500})},telegram:{async edit(){},async reply(){},async invoke(){},async getReply(){},async withClient(op,signal){return op({},signal);}}});await host.load(plugin(id));assert.equal((await host.unload(id,2000)).completed,true);await host.load(plugin(id));assert.equal((await host.shutdown(2000)).completed,true);await fs.rm(root,{recursive:true,force:true});}t.assert.ok(true);});
