'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const core=path.resolve(__dirname,'../../TeleBox-Core'),{buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs')),{PluginHost}=require(path.join(core,'dist/v2/host.js')),Database=require(path.join(core,'node_modules/better-sqlite3'));
const create=require(path.join(buildPlugin({id:'leech',packageRoot:path.resolve(__dirname,'../leech'),entry:'v2.ts'}).artifactDir,'index.cjs')).default;
const ts=(text)=>Math.floor(new Date(text).getTime()/1000);
async function fixture(t,options={}){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'leech-v2-'))),edits=[],replies=[],logs=[],calls=[];let replyAttempts=0;let batches=options.batches??[[{id:3,date:ts('2026-01-02T12:00:00'),senderId:900719925474099312345n,sender:{username:'alice',firstName:'A'},message:'three',media:{className:'MessageMediaPhoto'}},{id:2,date:ts('2026-01-01T12:00:00'),senderId:2n,message:'two'}],[{id:1,date:ts('2025-12-31T12:00:00'),senderId:1n,message:'old'}]];const client={async getMe(){await options.getMe?.();return options.me??{id:900719925474099312345n,username:'me',firstName:'Me'};},async getEntity(value){calls.push({kind:'entity',value});return options.entity??{className:'Channel',id:900719925474099399999n,title:'Group <x>',broadcast:false};},async getMessages(entity,input){calls.push({kind:'messages',entity,input});if(options.getMessages) return options.getMessages();return batches.shift()??[];}};const host=new PluginHost({storageRoot:root,prefixes:options.prefixes,logger:{info(){},error(event){logs.push(event);}},telegram:{async edit(message,text,settings){edits.push({text,settings});},async reply(message,text,settings){replyAttempts++;if(replyAttempts===options.replyFailsAt)throw new Error('private reply');replies.push({text,settings});},async invoke(){assert.fail('unexpected invoke');},async getReply(){},async withClient(operation,signal){return operation(client,signal);}}});await host.load(create());t.after(async()=>{await host.shutdown(1000);await fs.rm(root,{recursive:true,force:true});});return{root,edits,replies,logs,calls,host,run:(text,extra={})=>host.dispatchPrimary({id:7,chatId:'-100900719925474099388888',senderId:'900719925474099377777',outgoing:true,text,raw:{peerId:{exact:'peer'}},...extra}),rows(table){const database=new Database(path.join(root,'leech/leech.sqlite'),{readonly:true});database.defaultSafeIntegers(true);try{return database.prepare(`SELECT * FROM ${table} ORDER BY 1`).all();}finally{database.close();}}};}

test('leech help exposes restored commands with an escaped active prefix',async t=>{const f=await fixture(t,{prefixes:['<&']});await f.run('<&leech help');assert.match(f.edits.at(-1).text,/&lt;&amp;leech chat here/);assert.match(f.edits.at(-1).text,/leech jobs/);assert.doesNotMatch(f.edits.at(-1).text,/尚未实现|正在迁移/);assert.equal(f.calls.length,0);});

test('leech session preserves an exact account id and escapes profile fields',async t=>{const f=await fixture(t);await f.run('.leech login');assert.match(f.edits.at(-1).text,/900719925474099312345/);assert.match(f.edits.at(-1).text,/@me/);});

test('leech archives paged messages with progress, exact ids and a completed job',async t=>{const f=await fixture(t);await f.run('.leech chat here --from 2026-01-01 --to 2026-01-02 --batch 2');const messages=f.rows('leech_messages'),jobs=f.rows('leech_jobs');assert.equal(messages.length,2);assert.equal(messages[1].sender_id,'900719925474099312345');assert.equal(messages[1].chat_id,'-100900719925474099399999');assert.equal(messages[1].media_type,'MessageMediaPhoto');assert.equal(jobs[0].status,'completed');assert.equal(Number(jobs[0].saved_count),2);assert.equal(Number(jobs[0].scanned_count),3);assert.match(f.edits[0].text,/Leech started/);assert.match(f.edits[1].text,/Leech progress/);assert.match(f.edits.at(-1).text,/from_boundary_reached/);assert.equal(f.calls[0].value.exact,'peer');});

test('leech supports aliases, clamps input and rejects malformed ranges before Telegram work',async t=>{const f=await fixture(t);for(const sub of ['chat','group','messages']){await f.run(`.leech ${sub} @name --from 2026-01-02 --to 2026-01-01`);assert.match(f.edits.at(-1).text,/参数无效/);}assert.equal(f.calls.length,0);await f.run('.leech chat @name -f 2026-01-01 -t 2026-01-02 -b 999 -l 1');const call=f.calls.find(value=>value.kind==='messages');assert.equal(call.input.limit,1);});

test('leech lists jobs and stats from managed SQLite without deleting output',async t=>{const f=await fixture(t);await f.run('.leech chat here --from 2026-01-01 --to 2026-01-02 --limit 1');await f.run('.leech jobs 5');assert.match(f.edits.at(-1).text,/saved=1/);await f.run('.leech stats');assert.match(f.edits.at(-1).text,/Messages: <code>1<\/code>/);await f.run('.leech db');assert.match(f.edits.at(-1).text,/assets\/leech\/leech.sqlite/);});

test('leech cancellation waits for borrowed Telegram work and setup recovers the stale job',async t=>{const started=Promise.withResolvers(),release=Promise.withResolvers();const f=await fixture(t,{getMessages:async()=>{started.resolve();await release.promise;return[];}});const running=f.run('.leech chat here --from 2026-01-01 --to 2026-01-02');await started.promise;const unloading=f.host.unload('leech',1000);let done=false;unloading.then(()=>{done=true;});await new Promise(resolve=>setImmediate(resolve));assert.equal(done,false);release.resolve();assert.equal((await unloading).completed,true);await running.catch(()=>undefined);assert.deepEqual(f.logs,[]);assert.equal(f.edits.some(item=>/completed|归档失败/.test(item.text)),false);assert.equal(f.rows('leech_jobs')[0].status,'running');await f.host.load(create());const recovered=f.rows('leech_jobs')[0];assert.equal(recovered.status,'failed');assert.equal(recovered.error_kind,'INTERRUPTED');});

test('leech accepts negative targets and converts rawless chat ids without precision loss',async t=>{const explicit=await fixture(t,{batches:[[]]});await explicit.run('.leech chat -100900719925474099399999 --from 2026-01-01 --to 2026-01-02');assert.equal(explicit.calls[0].value.toString(),'-100900719925474099399999');assert.equal(typeof explicit.calls[0].value,'object');const current=await fixture(t,{batches:[[]]});await current.run('.leech chat here --from 2026-01-01 --to 2026-01-02',{raw:undefined});assert.equal(current.calls[0].value.toString(),'-100900719925474099388888');assert.equal(typeof current.calls[0].value,'object');});

test('leech upsert refreshes every mutable message field',async t=>{const base={id:9,date:ts('2026-01-01T12:00:00'),senderId:1n,sender:{username:'old',firstName:'Old'},message:'old',media:{className:'OldMedia'},replyToMsgId:1,groupedId:2n,views:3,forwards:4,out:false};const newer={...base,senderId:5n,sender:{username:'new',firstName:'New'},message:'new',media:{className:'NewMedia'},replyToMsgId:6,groupedId:7n,views:8,forwards:9,out:true};const f=await fixture(t,{batches:[[base],[],[newer],[]]});await f.run('.leech chat here --from 2026-01-01 --to 2026-01-02 --batch 1');await f.run('.leech chat here --from 2026-01-01 --to 2026-01-02 --batch 1');const row=f.rows('leech_messages')[0];assert.equal(row.sender_id,'5');assert.equal(row.sender_username,'new');assert.equal(row.sender_name,'New');assert.equal(row.message_text,'new');assert.equal(row.media_type,'NewMedia');assert.equal(Number(row.reply_to_msg_id),6);assert.equal(row.grouped_id,'7');assert.equal(Number(row.views),8);assert.equal(Number(row.forwards),9);assert.equal(Number(row.is_out),1);});

test('leech counts only committed rows when a later batch SQL write rolls back',async t=>{const first={id:2,date:ts('2026-01-02T12:00:00'),senderId:2n,message:'saved'};const invalid={id:1,date:ts('2026-01-01T12:00:00'),senderId:1n,sender:{username:{unsupported:true}},message:'rollback'};const f=await fixture(t,{batches:[[first],[invalid]]});await f.run('.leech chat here --from 2026-01-01 --to 2026-01-02 --batch 1');const job=f.rows('leech_jobs')[0];assert.equal(job.status,'failed');assert.equal(Number(job.saved_count),1);assert.equal(f.rows('leech_messages').length,1);assert.deepEqual(f.logs,['leech_archive_failed']);});

test('leech keeps a completed archive completed when paginated result delivery is partial',async t=>{const f=await fixture(t,{entity:{className:'Channel',id:1n,title:'T'.repeat(4000),broadcast:false},batches:[[{id:1,date:ts('2026-01-01T12:00:00'),message:'x'}]],replyFailsAt:1});await f.run('.leech chat here --from 2026-01-01 --to 2026-01-02 --limit 1');assert.equal(f.rows('leech_jobs')[0].status,'completed');assert.ok(f.edits.some(item=>/1\/\d+ 页/.test(item.text)));assert.match(f.replies.at(-1).text,/已发送 1\/\d+ 页/);assert.deepEqual(f.logs,['leech_result_delivery_failed']);});

test('leech paginates long session names and twenty long job titles',async t=>{const session=await fixture(t,{me:{id:1n,firstName:'N'.repeat(8000)}});await session.run('.leech session');assert.ok(session.replies.length>0);assert.match([session.edits.at(-1).text,...session.replies.map(item=>item.text)].join(''),/N{1000}/);const jobs=await fixture(t,{entity:{className:'Channel',id:1n,title:'J'.repeat(500),broadcast:false},getMessages:async()=>[]});for(let index=0;index<20;index++)await jobs.run('.leech chat here --from 2026-01-01 --to 2026-01-02');const before=jobs.replies.length;await jobs.run('.leech jobs 20');assert.ok(jobs.replies.length>before);assert.ok([jobs.edits.at(-1),...jobs.replies.slice(before)].every(item=>item.text.length<=3500));});

test('leech exposes only fixed session and archive failures',async t=>{const session=await fixture(t,{getMe:async()=>{throw Object.assign(new Error('private'),{code:'SECRET'});}});await session.run('.leech session');assert.deepEqual(session.logs,['leech_session_failed']);assert.doesNotMatch(JSON.stringify(session.edits),/private|SECRET/);const archive=await fixture(t,{getMessages:async()=>{throw new Error('private archive');}});await archive.run('.leech chat here --from 2026-01-01 --to 2026-01-02');assert.deepEqual(archive.logs,['leech_archive_failed']);assert.doesNotMatch(JSON.stringify(archive.edits),/private archive/);});
