'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const core=path.resolve(__dirname,'../../TeleBox-Core');
const {buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs'));
const {PluginHost}=require(path.join(core,'dist/v2/host.js'));
function create(id){const {artifactDir}=buildPlugin({id,packageRoot:path.resolve(__dirname,`../${id}`),entry:'v2.ts'});return require(path.join(artifactDir,'index.cjs')).default();}
async function fixture(t,id,fetch,extra={}){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),`mibot-${id}-`))),edits=[],requests=[];const telegram={async edit(_m,text,options){edits.push({text,options});},async reply(){},async invoke(){},async getReply(){},async withClient(op,signal){return op(extra.client??{},signal);}};const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},processes:{timeoutMs:120000,maxOutputBytes:1048576,concurrency:1,queueCapacity:8},http:{fetch:async(url,init)=>{requests.push({url:new URL(url),init});return fetch(new URL(url),init);}},telegram,...extra.host});await host.load(create(id));t.after(async()=>{assert.equal((await host.shutdown(2000)).completed,true);await fs.rm(root,{recursive:true,force:true});});return{root,host,edits,requests,run:(text,saved=true)=>host.dispatchPrimary({id:1,chatId:saved?'1':'-10099',senderId:'1',outgoing:true,saved,text,raw:{peerId:{}}})};}

test('checkapi keeps credentials private, validates writes, and replaces duplicate names',async t=>{let valid=false;const f=await fixture(t,'checkapi',async(_u,init)=>valid?Response.json({data:[{id:'m1'}]}):new Response(JSON.stringify({error:{message:'bad secret'}}),{status:401}));await f.run('.checkapi save prod https://api.example.test sk-secret',false);assert.match(f.edits.at(-1).text,/仅限收藏夹/);await f.run('.checkapi save prod https://api.example.test sk-secret');assert.match(f.edits.at(-1).text,/验证失败/);valid=true;await f.run('.checkapi save prod https://api.example.test sk-new-secret');assert.match(f.edits.at(-1).text,/更新.*验证成功/);await f.run('.checkapi list');assert.doesNotMatch(f.edits.at(-1).text,/sk-new-secret/);assert.equal(f.requests.at(-1).url.hostname,'api.example.test');await f.run('.checkapi models prod',false);assert.match(f.edits.at(-1).text,/m1/);await f.run('.checkapi del prod',false);assert.match(f.edits.at(-1).text,/已删除/);});

test('komari validates response structures and uses exact redirect allowlist',async t=>{const data={"/api/public":{status:'success',data:{sitename:'Site <x>'}},"/api/version":{status:'success',data:{version:'1',hash:'a'}},"/api/nodes":{status:'success',data:[{name:'n',cpu_cores:2,mem_total:1024}]}};const f=await fixture(t,'komari',async u=>Response.json(data[Object.keys(data).find(key=>u.pathname.endsWith(key))]??{status:'error'}));await f.run('.komari _set_url https://komari.example.test',false);assert.doesNotMatch(f.edits.at(-1).text,/收藏夹/);await f.run('.komari status');assert.match(f.edits.at(-1).text,/Site &lt;x&gt;/);assert.ok(f.requests.every(x=>x.url.hostname==='komari.example.test'));});

test('nezha verifies secret configuration and never echoes credentials or provider details',async t=>{let authorized=false;const f=await fixture(t,'nezha',async(_u,init)=>{authorized=String(init.headers.cookie||'').startsWith('nz-jwt=');return Response.json({success:true,data:[{id:1,name:'node',last_active:new Date().toISOString(),host:{mem_total:100},state:{cpu:2,mem_used:20}}]});});await f.run('.nezha set https://nezha.example.test top-secret',false);assert.match(f.edits.at(-1).text,/收藏夹/);await f.run('.nezha set https://nezha.example.test top-secret');assert.equal(authorized,true);assert.ok(f.edits.every(x=>!x.text.includes('top-secret')));await f.run('.nezha service off',false);assert.match(f.edits.at(-1).text,/设置已更新/);await f.run('.nezha');assert.match(f.edits.at(-1).text,/node/);assert.equal(f.requests.at(-1).url.hostname,'nezha.example.test');});

test('openlist restricts password setup while allowing group operations and reports authentication failure without leaking password',async t=>{const f=await fixture(t,'openlist',async()=>new Response(JSON.stringify({code:401,message:'bad super-secret'}),{status:401}));await f.run('.op login admin super-secret',false);assert.match(f.edits.at(-1).text,/收藏夹/);await f.run('.op login admin super-secret');assert.ok(f.edits.every(x=>!x.text.includes('super-secret')));await f.run('.op setdefault /dst',false);assert.match(f.edits.at(-1).text,/已更新/);await f.run('.op save /dst',false);assert.match(f.edits.at(-1).text,/请回复媒体文件/);});

test('legacy JSON migrations are idempotent across reloads',async t=>{for(const [id,file,legacy,command,expected] of [['checkapi','keys.json',[{name:'old',key:'legacy-secret',baseUrl:'https://old.example.test',addedAt:1}],'.checkapi list',/old/],['nezha','config.json',{url:'https://nezha.example.test',secret:'legacy-secret',serviceMonitor:false},'.nezha service on',/设置已更新/],['openlist','credentials.json',{username:'legacy',password:'legacy-secret',defaultPath:'/legacy'},'.op login next next-secret',/已保存/]]){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),`mibot-migrate-${id}-`)));await fs.mkdir(path.join(root,id),{recursive:true});await fs.writeFile(path.join(root,id,file),JSON.stringify(legacy));const edits=[];const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},processes:{timeoutMs:120000,maxOutputBytes:1048576,concurrency:1,queueCapacity:8},http:{fetch:async()=>Response.json({success:true,data:[]})},telegram:{async edit(_m,text){edits.push(text);},async reply(){},async invoke(){},async getReply(){},async withClient(op,signal){return op({},signal);}}});await host.load(create(id));await host.dispatchPrimary({id:1,chatId:'1',senderId:'1',outgoing:true,saved:true,text:command,raw:{peerId:{}}});assert.match(edits.at(-1),expected);assert.equal((await host.unload(id,1000)).completed,true);await host.load(create(id));assert.equal((await host.shutdown(1000)).completed,true);const output=id==='checkapi'?'keys-v2.json':id==='openlist'?'credentials-v2.json':'config-v2.json';const migrated=JSON.parse(await fs.readFile(path.join(root,id,output),'utf8'));assert.equal(migrated.legacyImported,true);if(id==='checkapi')assert.equal(migrated.entries.length,1);await fs.rm(root,{recursive:true,force:true});}t.assert.ok(true);});

test('all four artifacts load, unload, and reload through PluginHost',async t=>{for(const id of ['checkapi','komari','nezha','openlist']){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),`mibot-reload-${id}-`)));const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},processes:{timeoutMs:120000,maxOutputBytes:1048576,concurrency:1,queueCapacity:8},http:{fetch:async()=>Response.json({})},telegram:{async edit(){},async reply(){},async invoke(){},async getReply(){},async withClient(op,signal){return op({},signal);}}});await host.load(create(id));assert.equal((await host.unload(id,2000)).completed,true);await host.load(create(id));assert.equal((await host.shutdown(2000)).completed,true);await fs.rm(root,{recursive:true,force:true});}t.assert.ok(true);});
