'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {execFileSync}=require('node:child_process');
const core=path.resolve(__dirname,'../../TeleBox-Core'),{buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs')),{PluginHost}=require(path.join(core,'dist/v2/host.js'));
const built=buildPlugin({id:'nezha',packageRoot:path.resolve(__dirname,'../nezha'),entry:'v2.ts'}),create=require(path.join(built.artifactDir,'index.cjs')).default;
async function hostFixture(t,{legacy,current,fetch,prefixes}={}){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'nezha-compat-')));await fs.mkdir(path.join(root,'nezha'));if(legacy)await fs.writeFile(path.join(root,'nezha','config.json'),JSON.stringify(legacy));if(current)await fs.writeFile(path.join(root,'nezha','config-v2.json'),JSON.stringify(current));const edits=[],replies=[],logs=[],host=new PluginHost({storageRoot:root,prefixes,logger:{info(event,fields){logs.push({event,fields});},error(){}},telegram:{async edit(_m,text,options){edits.push({text,options});},async reply(_m,text,options){replies.push({text,options});},async invoke(){},async getReply(){},async withClient(fn,signal){return fn({},signal);}},http:{fetch:fetch??(async()=>Response.json({success:true,data:[]}))}});await host.load(create());t.after(async()=>{await host.shutdown(2000);await fs.rm(root,{recursive:true,force:true});});return{root,host,edits,replies,logs,run:(text='.nezha',fields={})=>host.dispatchPrimary({id:1,chatId:'1',senderId:'1',outgoing:true,text,...fields})};}

test('nezha migration preserves every explicitly present V2 field over legacy values',async t=>{const f=await hostFixture(t,{legacy:{url:'https://legacy.invalid/base/',secret:'legacy-secret',serviceMonitor:true,unknownLegacy:'old'},current:{schemaVersion:1,url:'',secret:'',serviceMonitor:false,legacyImported:false,unknownV2:'keep'}});const saved=JSON.parse(await fs.readFile(path.join(f.root,'nezha','config-v2.json')));assert.deepEqual(saved,{schemaVersion:1,url:'',secret:'',serviceMonitor:false,legacyImported:true,unknownV2:'keep'});assert.equal((await f.host.unload('nezha',1000)).completed,true);await fs.writeFile(path.join(f.root,'nezha','config.json'),'{broken');await f.host.load(create());assert.deepEqual(JSON.parse(await fs.readFile(path.join(f.root,'nezha','config-v2.json'))),saved);});

test('nezha malformed legacy configuration does not mark migration and succeeds on retry',async t=>{const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'nezha-migrate-retry-')));await fs.mkdir(path.join(root,'nezha'));await fs.writeFile(path.join(root,'nezha','config.json'),'{broken');const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},telegram:{async edit(){},async reply(){},async invoke(){},async getReply(){},async withClient(fn,signal){return fn({},signal);}}});t.after(async()=>{await host.shutdown(1000);await fs.rm(root,{recursive:true,force:true});});await assert.rejects(host.load(create()));await assert.rejects(fs.readFile(path.join(root,'nezha','config-v2.json')),{code:'ENOENT'});await fs.writeFile(path.join(root,'nezha','config.json'),JSON.stringify({url:'https://legacy.invalid',secret:'legacy-secret',serviceMonitor:false}));await host.load(create());const saved=JSON.parse(await fs.readFile(path.join(root,'nezha','config-v2.json')));assert.deepEqual({url:saved.url,secret:saved.secret,serviceMonitor:saved.serviceMonitor,legacyImported:saved.legacyImported},{url:'https://legacy.invalid',secret:'legacy-secret',serviceMonitor:false,legacyImported:true});});

for(const [label,invalid] of [['null',null],['array',[]],['number',7],['string','bad']])for(const file of ['config-v2.json','config.json'])test(`nezha rejects ${label} root in ${file} and retries after repair`,async t=>{const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'nezha-root-type-'))),directory=path.join(root,'nezha');await fs.mkdir(directory);const invalidPath=path.join(directory,file),legacyPath=path.join(directory,'config.json'),currentPath=path.join(directory,'config-v2.json');await fs.writeFile(invalidPath,JSON.stringify(invalid));if(file==='config-v2.json')await fs.writeFile(legacyPath,JSON.stringify({url:'https://legacy.invalid',secret:'legacy-secret',serviceMonitor:false}));const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},telegram:{async edit(){},async reply(){},async invoke(){},async getReply(){},async withClient(fn,signal){return fn({},signal);}}});t.after(async()=>{await host.shutdown(1000);await fs.rm(root,{recursive:true,force:true});});await assert.rejects(host.load(create()),/Invalid Nezha configuration root/);assert.deepEqual(JSON.parse(await fs.readFile(invalidPath)),invalid);if(file==='config.json')await assert.rejects(fs.readFile(currentPath),{code:'ENOENT'});else assert.notEqual(JSON.parse(await fs.readFile(currentPath))?.legacyImported,true);if(file==='config-v2.json')await fs.writeFile(currentPath,'{}');else await fs.writeFile(legacyPath,JSON.stringify({url:'https://legacy.invalid',secret:'legacy-secret',serviceMonitor:false}));await host.load(create());const saved=JSON.parse(await fs.readFile(currentPath));assert.equal(saved.legacyImported,true);assert.equal(saved.url,'https://legacy.invalid');});

test('nezha cancellation during legacy read never writes the migration marker',async t=>{const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'nezha-migrate-cancel-'))),fifo=path.join(root,'config.json');t.after(()=>fs.rm(root,{recursive:true,force:true}));execFileSync('mkfifo',[fifo]);const controller=new AbortController();let state={schemaVersion:1,url:'',secret:'',serviceMonitor:true,legacyImported:false},updates=0;const context={signal:controller.signal,files:{dataPath:name=>path.join(root,name)},storage:{json:()=>({async read(){return structuredClone(state);},async update(fn){updates++;state=await fn(structuredClone(state));return state;}})}};const loading=create().setup(context),rejected=assert.rejects(loading,{name:'AbortError'});await new Promise(resolve=>setTimeout(resolve,20));controller.abort();await fs.writeFile(fifo,'{}').catch(error=>{if(error.code!=='EPIPE')throw error;});await rejected;assert.equal(updates,0);assert.equal(state.legacyImported,false);await assert.rejects(fs.readFile(path.join(root,'config-v2.json')),{code:'ENOENT'});});

test('nezha help and service status escape the active prefix without HTTP',async t=>{let fetches=0;const f=await hostFixture(t,{prefixes:['<&'],current:{schemaVersion:1,url:'https://panel.invalid',secret:'secret',serviceMonitor:false,legacyImported:true},fetch:async()=>{fetches++;return Response.json({success:true,data:[]});}});await f.run('<&nezha help');assert.match(f.edits.at(-1).text,/&lt;&amp;nezha set/);await f.run('<&nezha service');assert.match(f.edits.at(-1).text,/当前状态: <b>关闭/);assert.match(f.edits.at(-1).text,/&lt;&amp;nezha service on\/off/);assert.doesNotMatch(f.edits.at(-1).text,/<&/);assert.equal(fetches,0);});

test('nezha chart detail matches a case-insensitive partial node name',async t=>{const requests=[];const png=Buffer.from('89504e470d0a1a0a','hex'),f=await hostFixture(t,{current:{schemaVersion:1,url:'https://panel.invalid/base',secret:'secret',serviceMonitor:false,legacyImported:true},fetch:async url=>{const target=new URL(url);requests.push(target.pathname);if(target.pathname.endsWith('/server'))return Response.json({success:true,data:[{id:7,name:'Hong Kong Node'}]});if(target.hostname==='panel.invalid')return Response.json({success:true,data:[{monitor_name:'HTTPS',created_at:[1],avg_delay:[2]}]});return new Response(png);}});await f.run('.nezha chart hong kong');assert.deepEqual(requests.slice(0,2),['/base/api/v1/server','/base/api/v1/service/7']);});

test('nezha unload cancels a hanging list body and waits for asynchronous body cleanup',async t=>{let cancelResolve,startedResolve,cancelStartedResolve;const cleanup=new Promise(resolve=>{cancelResolve=resolve;}),started=new Promise(resolve=>{startedResolve=resolve;}),cancelStarted=new Promise(resolve=>{cancelStartedResolve=resolve;});let body;const f=await hostFixture(t,{current:{schemaVersion:1,url:'https://panel.invalid',secret:'secret',serviceMonitor:false,legacyImported:true},fetch:async()=>{body=new ReadableStream({pull(){startedResolve();return new Promise(()=>{});},cancel(){cancelStartedResolve();return cleanup;}});return new Response(body);}});const running=f.run();await started;while(!body.locked)await new Promise(resolve=>setImmediate(resolve));let settled=false;const unloading=f.host.unload('nezha',1000).then(value=>{settled=true;return value;});await cancelStarted;await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);cancelResolve();assert.equal((await unloading).completed,true);await running;assert.equal(body.locked,false);assert.equal(f.edits.length,1);});

test('nezha never exposes arbitrary transport names or messages',async t=>{const f=await hostFixture(t,{current:{schemaVersion:1,url:'https://panel.invalid',secret:'secret',serviceMonitor:false,legacyImported:true},fetch:async()=>{const error=new Error('https://user:pass@secret.invalid/private');error.name='MaliciousTransport';throw error;}});await f.run();assert.equal(f.edits.at(-1).text,'❌ 哪吒请求失败，请稍后重试');assert.doesNotMatch(JSON.stringify({edits:f.edits,logs:f.logs}),/user:pass|secret\.invalid|MaliciousTransport/);});
