'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const core=path.resolve(__dirname,'../../TeleBox-Core'),{buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs')),{PluginHost}=require(path.join(core,'dist/v2/host.js')),{definePlugin}=require(path.join(core,'dist/v2/sdk.js')),{Api}=require(path.join(core,'node_modules/teleproto')),{returnBigInt}=require(path.join(core,'node_modules/teleproto/Helpers.js'));
const {artifactDir}=buildPlugin({id:'quote-messages',packageRoot:path.resolve(__dirname,'../quote'),entry:'v2/messages.ts'}),{toQuoteMessages}=require(path.join(artifactDir,'index.cjs'));
async function hostFixture(t,client){const root=await fs.mkdtemp(path.join(os.tmpdir(),'quote-messages-'));let output;const plugin=definePlugin({apiVersion:1,id:'quote_messages_test',description:'test',commands:{q:{description:'test',async handle(i,c){output=await toQuoteMessages(c,[{raw:i.message.raw,envelope:i.message}],{replies:true,media:false,crop:false,scale:2,hidden:false});}}}});const host=new PluginHost({storageRoot:root,telegram:{async edit(){},async reply(){},async invoke(r){return client.invoke(r);},async getReply(){},async withClient(fn,signal){return fn(client,signal);}}});await host.load(plugin);t.after(async()=>{await host.shutdown(1000);await fs.rm(root,{recursive:true,force:true});});return{host,run:raw=>host.dispatchPrimary({id:90,chatId:'9',senderId:'8',outgoing:true,text:'.q',raw}),output:()=>output};}

test('full payload preserves TL entities, forwarded identity and nested voice reply through a real Host',async t=>{const voice={id:4,peerId:returnBigInt(9),senderId:returnBigInt(6),sender:{id:returnBigInt(6),firstName:'Reply'},message:'',media:{className:'MessageMediaDocument',document:{attributes:[{className:'DocumentAttributeAudio',voice:true,duration:7,waveform:Buffer.from([1,40])}]}}};const client={async invoke(){return[];},async getEntity(){return{id:returnBigInt(44),accessHash:returnBigInt(45),firstName:'Origin'};},async getMessages(){return[voice];},async downloadProfilePhoto(){},async *iterDownload(){}};const f=await hostFixture(t,client);const raw={id:5,peerId:returnBigInt(9),senderId:returnBigInt(8),sender:{id:returnBigInt(8),firstName:'Forwarder'},message:'hello',entities:[{className:'MessageEntityBlockquote',offset:0,length:5},{className:'MessageEntityMentionName',offset:0,length:5,userId:returnBigInt(77)}],fwdFrom:{fromId:returnBigInt(44)},replyToMsgId:4};await f.run(raw);const item=f.output()[0];assert.equal(item.from.id,'44');assert.equal(item.from.name,'Origin');assert.equal(item.forward.label,'Origin');assert.deepEqual(item.entities.map(x=>x.type),['blockquote','text_mention']);assert.equal(item.entities[1].user,'77');assert.deepEqual(item.replyMessage.voice.waveform,[1,31]);assert.equal(item.replyMessage.voice.duration,7);});

test('ordinary photo preserves source dimensions without the media flag and receives the Host signal',async t=>{const sharp=require(path.join(core,'node_modules/sharp')),png=await sharp({create:{width:4,height:2,channels:4,background:'#fff'}}).png().toBuffer();let downloadSignal;const client={async invoke(){return[];},async *iterDownload(_media,options){downloadSignal=options.signal;yield png;},async downloadProfilePhoto(){}};const f=await hostFixture(t,client);await f.run({id:5,peerId:returnBigInt(9),senderId:returnBigInt(8),sender:{id:returnBigInt(8),firstName:'Photo'},message:'',media:{className:'MessageMediaPhoto'}});const item=f.output()[0];assert.ok(item.mediaBuffer.length);assert.equal(item.mediaCanvas.width,4);assert.equal(item.mediaCanvas.height,2);assert.equal(downloadSignal.aborted,false);});

test('unload actively aborts a hanging media iterator and emits no late payload',async t=>{let observed;const client={async invoke(){return[];},async downloadProfilePhoto(){},iterDownload(_media,{signal}){return{[Symbol.asyncIterator](){return this;},next(){return new Promise((_,reject)=>{signal.addEventListener('abort',()=>{observed=true;reject(signal.reason);},{once:true});});}};}};const f=await hostFixture(t,client),pending=f.run({id:5,peerId:returnBigInt(9),senderId:returnBigInt(8),sender:{id:returnBigInt(8),firstName:'Photo'},message:'',media:{className:'MessageMediaPhoto'}}),rejected=assert.rejects(pending);await new Promise(resolve=>setImmediate(resolve));assert.equal((await f.host.unload('quote_messages_test',1000)).completed,true);await rejected;assert.equal(observed,true);assert.equal(f.output(),undefined);});

test('video preview uses a bounded managed ffmpeg argv and reads only its limited PNG output',async t=>{const sharp=require(path.join(core,'node_modules/sharp')),png=await sharp({create:{width:2,height:2,channels:4,background:'#fff'}}).png().toBuffer(),root=await fs.mkdtemp(path.join(os.tmpdir(),'quote-video-')),calls=[];t.after(()=>fs.rm(root,{recursive:true,force:true}));const signal=new AbortController().signal,client={async invoke(){return[];},async downloadProfilePhoto(){},async *iterDownload(){yield Buffer.from('video');}};const context={signal,log:{},telegram:{withClient:fn=>fn(client,signal)},files:{async withTemp(fn){return fn(root,signal);}},processes:{async run(command,args,options){calls.push({command,args,options});await fs.writeFile(args.at(-1),png);return{stdout:Buffer.alloc(0),stderr:Buffer.alloc(0),exitCode:0};}}};const raw={id:5,peerId:returnBigInt(9),senderId:returnBigInt(8),sender:{id:returnBigInt(8),firstName:'Video'},message:'',media:{className:'MessageMediaDocument',document:{size:5,attributes:[{className:'DocumentAttributeVideo',duration:3}]}}};const [item]=await toQuoteMessages(context,[{raw}],{replies:false,media:false,crop:false,scale:2,hidden:false});assert.ok(item.mediaCanvas);assert.equal(calls.length,1);assert.ok(path.isAbsolute(calls[0].command));assert.equal(calls[0].options.cwd,root);assert.equal(calls[0].options.timeoutMs,15000);assert.equal(calls[0].options.signal.aborted,false);assert.deepEqual(calls[0].args.slice(4,7),['-protocol_whitelist','file','-i']);assert.ok(calls[0].args.includes('-fs'));});

test('media option leaves pure text and audio attachments intact without decoding them',async t=>{let downloads=0;const signal=new AbortController().signal,client={async invoke(){return[];},async downloadProfilePhoto(){},async *iterDownload(){downloads++;yield Buffer.from('audio');}};const context={signal,telegram:{withClient:fn=>fn(client,signal)}};const text={id:1,sender:{id:returnBigInt(1),firstName:'Text'},message:'hello'},audio={id:2,sender:{id:returnBigInt(1),firstName:'Text'},message:'song',media:{className:'MessageMediaDocument',document:{size:5,attributes:[{className:'DocumentAttributeAudio',title:'Title',performer:'Artist',duration:9}]}}};const result=await toQuoteMessages(context,[{raw:text},{raw:audio}],{replies:false,media:true,crop:false,scale:2,hidden:false});assert.equal(downloads,0);assert.equal(result[0].text,'hello');assert.deepEqual(result[1].audio,{title:'Title',performer:'Artist',duration:9});});

test('avatar remains a square PNG Buffer and total source text is bounded',async t=>{const sharp=require(path.join(core,'node_modules/sharp')),png=await sharp({create:{width:4,height:2,channels:4,background:'#fff'}}).png().toBuffer(),signal=new AbortController().signal,client={async invoke(){return[];},async downloadProfilePhoto(){return png;}};const context={signal,telegram:{withClient:fn=>fn(client,signal)}};const raw={id:1,sender:{id:returnBigInt(1),firstName:'Avatar'},message:'ok'};const [item]=await toQuoteMessages(context,[{raw}],{replies:false,media:false,crop:false,scale:2,hidden:false});assert.ok(Buffer.isBuffer(item.avatarBuffer));const meta=await sharp(item.avatarBuffer).metadata();assert.equal(meta.width,128);assert.equal(meta.height,128);await assert.rejects(()=>toQuoteMessages(context,Array.from({length:7},(_,i)=>({raw:{id:i+1,sender:raw.sender,message:'x'.repeat(4000)}})),{replies:false,media:false,crop:false,scale:2,hidden:true}),/QUOTE_TEXT_LIMIT/);});

test('custom emoji hydration scans identities and nested replies after entity resolution',async()=>{const sharp=require(path.join(core,'node_modules/sharp')),png=await sharp({create:{width:2,height:2,channels:4,background:'#fff'}}).png().toBuffer(),signal=new AbortController().signal,documents=[{id:returnBigInt(123)},{id:returnBigInt(124)}],reply={id:2,peerId:returnBigInt(9),sender:{id:returnBigInt(2),firstName:'Reply'},message:'x',entities:[{className:'MessageEntityCustomEmoji',offset:0,length:1,documentId:returnBigInt(123)}]},client={async getEntity(){return{id:returnBigInt(44),firstName:'Origin',emojiStatus:{documentId:returnBigInt(124)}};},async getMessages(){return[reply];},async invoke(request){return request.className?.includes('GetCustomEmojiDocuments')?documents:[];},async *iterDownload(){yield png;},async downloadProfilePhoto(){}};const context={signal,telegram:{withClient:fn=>fn(client,signal)}};const raw={id:1,peerId:returnBigInt(9),sender:{id:returnBigInt(1),firstName:'Forwarder'},message:'root',fwdFrom:{fromId:returnBigInt(44)},replyToMsgId:2};const [item]=await toQuoteMessages(context,[{raw}],{replies:true,media:false,crop:false,scale:2,hidden:false});assert.ok(Buffer.isBuffer(item.emoji_status.customEmojiBuffer));assert.ok(Buffer.isBuffer(item.replyMessage.entities[0].customEmojiBuffer));});

test('non-raster TGS sticker uses a serialized InputDocumentFileLocation thumbnail',async()=>{const sharp=require(path.join(core,'node_modules/sharp')),png=await sharp({create:{width:2,height:2,channels:4,background:'#fff'}}).png().toBuffer(),signal=new AbortController().signal,thumb={className:'PhotoSize',type:'m',size:png.length};let downloads=0,location,downloadOptions;const client={async invoke(){return[];},async downloadProfilePhoto(){},async *iterDownload(target,options){downloads++;if(target instanceof Api.InputDocumentFileLocation){location=target;downloadOptions=options;yield png;}else yield Buffer.from([0x1f,0x8b,0,0]);}};const context={signal,telegram:{withClient:fn=>fn(client,signal)}};const raw={id:1,sender:{id:returnBigInt(1),firstName:'Sticker'},message:'',media:{className:'MessageMediaDocument',document:{id:returnBigInt(77),accessHash:returnBigInt(88),dcId:4,fileReference:Buffer.from([1]),mimeType:'application/x-tgsticker',attributes:[{className:'DocumentAttributeSticker'}],thumbs:[thumb]}}};const [item]=await toQuoteMessages(context,[{raw}],{replies:false,media:false,crop:false,scale:2,hidden:false});assert.equal(downloads,2);assert.equal(location.thumbSize,'m');assert.ok(location.getBytes().length>0);assert.equal(downloadOptions.dcId,4);assert.equal(downloadOptions.signal,signal);assert.ok(item.mediaCanvas);assert.equal(item.mediaType,'sticker');});
