'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
require(path.resolve(__dirname,'../../TeleBox-Core/node_modules/esbuild-register/dist/node')).register({target:'node24'});
const {createAssetLoader}=require('../quote/v2/assets.ts');
const names=["pattern_02.png","pattern_ny.png","emoji/emoji-apple-image.json","emoji/emoji-google-image.json","emoji/emoji-twitter-image.json","emoji/emoji-joypixels-image.json","emoji/emoji-blob-image.json","NotoSansCJK-Regular.ttc","NotoSansCJK-Bold.ttc"];
async function fixture(t,{missing,header=true,body=Buffer.from('asset')}={}){
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'quote-assets-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
  for(const name of names){const file=path.join(root,name);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,'seed');}
  if(missing)await fs.rm(path.join(root,missing));let fetches=0;const controller=new AbortController();
  const ctx={signal:controller.signal,files:{async dataFile(relative){const target=path.join(root,relative);await fs.mkdir(path.dirname(target),{recursive:true});return target;},dataPath(){return root;}},http:{async withResponse(_url,_init,consume){fetches++;return consume(new Response(body,{headers:header?{'content-length':String(body.length)}:{}}),controller.signal);}}};
  return{root,ctx,controller,get fetches(){return fetches;}};
}
test('reuses nine ordinary nonempty bounded files without network',async t=>{const f=await fixture(t);assert.equal(await createAssetLoader()(f.ctx),f.root);assert.equal(f.fetches,0);});
test('concurrent callers share one download and atomically publish mutable upstream content',async t=>{const f=await fixture(t,{missing:'pattern_02.png',body:Buffer.from('new-size')}),load=createAssetLoader();assert.deepEqual(await Promise.all([load(f.ctx),load(f.ctx)]),[f.root,f.root]);assert.equal(f.fetches,1);assert.equal(await fs.readFile(path.join(f.root,'pattern_02.png'),'utf8'),'new-size');assert.equal((await fs.readdir(f.root)).some(name=>name.endsWith('.tmp')),false);});
test('chunked response without Content-Length is accepted',async t=>{const f=await fixture(t,{missing:'pattern_02.png',header:false,body:Buffer.from('chunked')});assert.equal(await createAssetLoader()(f.ctx),f.root);assert.equal(await fs.readFile(path.join(f.root,'pattern_02.png'),'utf8'),'chunked');});
test('declared short response leaves no target and the same loader retries',async t=>{const f=await fixture(t,{missing:'pattern_02.png'}),load=createAssetLoader();let first=true;f.ctx.http.withResponse=async(_url,_init,consume)=>{const wasFirst=first;first=false;const bytes=wasFirst?Buffer.from('x'):Buffer.from('valid');return consume(new Response(bytes,{headers:{'content-length':wasFirst?'5':String(bytes.length)}}),f.controller.signal);};await assert.rejects(load(f.ctx));assert.equal(await fs.stat(path.join(f.root,'pattern_02.png')).then(()=>true,()=>false),false);assert.equal(await load(f.ctx),f.root);});
test('cancellation waits for the first reader cancel before release and removes temp',async t=>{const f=await fixture(t,{missing:'pattern_02.png'});let readResolve,cancelResolve,startResolve,cancels=0,released=false;const reading=new Promise(r=>{readResolve=r}),cleaned=new Promise(r=>{cancelResolve=r}),started=new Promise(r=>{startResolve=r});const reader={read(){startResolve();return reading;},async cancel(){cancels++;readResolve({done:true});await cleaned;},releaseLock(){released=true;}};f.ctx.http.withResponse=async(_u,_i,consume)=>consume({ok:true,headers:new Headers(),body:{getReader(){return reader;}}},f.controller.signal);const running=createAssetLoader()(f.ctx);await started;f.controller.abort(new Error('cancel'));await new Promise(setImmediate);assert.equal(cancels,1);assert.equal(released,false);cancelResolve();await assert.rejects(running,/cancel/);assert.equal(released,true);assert.equal(cancels,1);assert.equal((await fs.readdir(f.root)).some(name=>name.endsWith('.tmp')),false);});
