'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),os=require('node:os');
const core=path.resolve(__dirname,'../../TeleBox-Core');const {buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs'));const create=require(path.join(buildPlugin({id:'save',packageRoot:path.resolve(__dirname,'../save'),entry:'v2.ts'}).artifactDir,'index.cjs')).default;
function fixture({media=false,forwardError}={}){let data={schemaVersion:1,users:{}};const edits=[],forwards=[],sent=[],resolved=[],chunks=[];const root=fs.mkdtempSync(path.join(os.tmpdir(),'save-v2-'));const source={id:8,chatId:'-1007',peerId:'peer',text:'hello',...(media?{media:{document:{mimeType:'application/octet-stream',attributes:[]}}}:{})};const client={async getInputEntity(value){resolved.push(String(value));return value},async getMessages(){return[source]},async forwardMessages(target,options){forwards.push({target,options});if(forwardError)throw new Error(forwardError);return[{id:90}]},async sendMessage(target,options){sent.push({target,options});return{id:91}},async sendFile(target,options){sent.push({target,options,bytes:fs.readFileSync(options.file)});return{id:92}},async *iterDownload(){for(const chunk of [Buffer.from('stream-'),Buffer.from('media')]){chunks.push(chunk);yield chunk;}}};const signal=new AbortController().signal;const context={signal,telegram:{edit:async(m,text,o)=>edits.push({text,o}),getReply:async()=>undefined,withClient:fn=>fn(client,signal)},storage:{json(){return{async read(){return structuredClone(data)},async update(fn){data=await fn(structuredClone(data));return data}}}},files:{async dataDirectory(name){const dir=path.join(root,name);fs.mkdirSync(dir,{recursive:true});return dir},async withTemp(fn){const dir=fs.mkdtempSync(path.join(root,'job-'));try{return await fn(dir,signal)}finally{fs.rmSync(dir,{recursive:true,force:true})}},dataPath(){return root}}};return{root,edits,forwards,sent,resolved,chunks,data:()=>data,run:args=>create().commands.save.handle({message:{id:1,chatId:'1',senderId:'99',text:'.save '+args.join(' '),outgoing:true},args,command:'save',prefix:'.'},context),cleanup:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('save persists per-user target and source preferences',async t=>{const f=fixture();t.after(f.cleanup);await f.run(['to','@archive']);await f.run(['source','on']);assert.deepEqual(f.data().users['99'],{target:'@archive',showSource:true});});
test('save parses private links and forwards with explicit source peer',async t=>{const f=fixture();t.after(f.cleanup);await f.run(['https://t.me/c/7/8']);assert.ok(f.resolved.includes('-1007'));assert.equal(f.forwards[0].options.fromPeer,'peer');assert.deepEqual(f.forwards[0].options.messages,[8]);assert.match(f.edits.at(-1).text,/成功: 1\/1/);});
test('save rejects oversized ranges without touching Telegram history',async t=>{const f=fixture();t.after(f.cleanup);await f.run(['https://t.me/c/7/1|https://t.me/c/7/501']);assert.equal(f.forwards.length,0);assert.match(f.edits.at(-1).text,/最多保存 500/);});
test('save reports an inaccessible source as skipped instead of success',async t=>{const f=fixture();t.after(f.cleanup);f.forwards.length=0;await f.run(['not-a-link']);assert.equal(f.forwards.length,0);assert.match(f.edits.at(-1).text,/Prometheus/);});
test('save streams restricted media through a scoped temporary file',async t=>{const f=fixture({media:true,forwardError:'CHAT_FORWARDS_RESTRICTED'});t.after(f.cleanup);await f.run(['https://t.me/c/7/8']);assert.equal(f.chunks.length,2);assert.equal(f.sent[0].bytes.toString(),'stream-media');assert.match(f.edits.at(-1).text,/成功: 1\/1/);});
test('save imports the legacy prometheus user configuration once',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'save-v2-legacy-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'prometheus'));fs.mkdirSync(path.join(root,'save'));fs.writeFileSync(path.join(root,'prometheus','config.json'),JSON.stringify({users:{'99':{target:'@legacy',showSource:true}}}));let data={schemaVersion:1,users:{}};const edits=[];const context={signal:new AbortController().signal,log:{error(){}},telegram:{edit:async(m,text)=>edits.push(text)},storage:{json(){return{read:async()=>structuredClone(data),async update(fn){data=await fn(structuredClone(data));return data}}}},files:{dataPath:()=>path.join(root,'save')}};await create().commands.save.handle({message:{id:1,chatId:'1',senderId:'99',text:'.save target',outgoing:true},args:['target'],command:'save',prefix:'.'},context);assert.equal(data.users['99'].target,'@legacy');assert.match(edits[0],/@legacy/);});
