'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const core=path.resolve(__dirname,'../../TeleBox-Core');const {buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs'));const create=require(path.join(buildPlugin({id:'tmp_admin',packageRoot:path.resolve(__dirname,'../tmp_admin'),entry:'v2.ts'}).artifactDir,'index.cjs')).default;
function fixture(initial={schemaVersion:1,jobs:{},enabled:true}, initialParticipant){let data=structuredClone(initial),participant=initialParticipant??{className:'ChannelParticipant',rank:''};const edits=[],invokes=[],resources=[];const client={async getEntity(value){return String(value)==='7'?{className:'Channel',id:7n}:{className:'User',id:BigInt(String(value)),firstName:'Alice'}},async getInputEntity(value){const id=value.id??BigInt(String(value));return String(id)==='7'?{className:'InputPeerChannel',channelId:id,accessHash:70n}:{className:'InputPeerUser',userId:id,accessHash:420n}},async invoke(request){invokes.push(request);if(request.className==='channels.GetParticipant'||request.constructor?.name==='GetParticipant')return{participant};if(request.className==='channels.EditAdmin'||request.constructor?.name==='EditAdmin'){participant=request.adminRights?.other?{className:'ChannelParticipantAdmin',rank:request.rank,adminRights:request.adminRights}:{className:'ChannelParticipant',rank:''};return{}}},async sendMessage(){}};const signal=new AbortController().signal;const context={signal,telegram:{edit:async(m,text)=>edits.push(text),getReply:async()=>undefined,withClient:fn=>fn(client,signal)},storage:{json(){return{async read(){return structuredClone(data)},async update(fn){data=await fn(structuredClone(data));return data}}}},tasks:{add(label,cleanup){const item={label,cleanup};resources.push(item);return async()=>{const i=resources.indexOf(item);if(i>=0)resources.splice(i,1);await cleanup()}},run(label,fn){return Promise.resolve(fn(signal))}}};const plugin=create();return{plugin,edits,invokes,resources,data:()=>data,run:args=>plugin.commands.tmp_admin.handle({message:{id:10,chatId:'7',text:'.tmp_admin '+args.join(' '),outgoing:true,raw:{peerId:7n}},args,command:'tmp_admin',prefix:'.'},context),setup:()=>plugin.setup(context),cleanup:()=>plugin.cleanup(context)};}
test('tmp_admin persists a stable string-id expiry job and protects real admins',async()=>{const f=fixture();await f.setup();await f.run(['add','42','10']);assert.equal(Object.keys(f.data().jobs)[0],'7:42');assert.equal(f.data().jobs['7:42'].userId,'42');assert.equal(f.data().jobs['7:42'].channelAccessHash,'70');assert.equal(f.data().jobs['7:42'].userAccessHash,'420');assert.equal(f.resources.length,1);await f.run(['add','42','10']);assert.match(f.edits.at(-1),/已设置/);await f.cleanup();assert.equal(f.resources.length,0);});
test('tmp_admin setting disables mutations',async()=>{const f=fixture({schemaVersion:1,jobs:{},enabled:false});await f.setup();await f.run(['add','42']);assert.equal(f.invokes.length,0);assert.match(f.edits.at(-1),/关闭/);await f.cleanup();});
test('tmp_admin migrates legacy peer records without losing expiry state',async()=>{const legacy={jobs:{old:{chatKey:'7',channel:{channelId:'7',accessHash:'70'},user:{userId:'42',accessHash:'420'},userId:42,userDisplay:'Alice',expiresAt:Date.now()+60_000,retryCount:0}}};const f=fixture(legacy);await f.setup();assert.equal(f.data().schemaVersion,1);assert.equal(f.data().jobs['7:42'].channelAccessHash,'70');assert.equal(f.data().jobs['7:42'].userAccessHash,'420');assert.equal(f.resources.length,1);await f.cleanup();});

test('tmp_admin waits the full forty days and restores peers from persisted access hashes',async t=>{
  const now=Date.now(),period=40*24*60*60*1000;
  t.mock.timers.enable({apis:['Date','setTimeout'],now});
  const f=fixture({schemaVersion:1,enabled:true,jobs:{'7:42':{chatId:'7',userId:'42',display:'Alice',expiresAt:now+period,originalRank:'',retryCount:0,channelAccessHash:'70',userAccessHash:'420'}}},{className:'ChannelParticipantAdmin',rank:'临时管理',adminRights:{other:true}});
  t.after(()=>f.cleanup());await f.setup();
  const flush=()=>new Promise(resolve=>setImmediate(resolve));
  t.mock.timers.tick(2147483647);await flush();assert.equal(f.invokes.length,0);
  t.mock.timers.tick(period-2147483647-1);await flush();assert.equal(f.invokes.length,0);
  t.mock.timers.tick(1);await flush();await flush();
  const edit=f.invokes.find(r=>r.className==='channels.EditAdmin');assert.ok(edit);
  assert.equal(String(edit.channel.accessHash),'70');assert.equal(String(edit.userId.accessHash),'420');
  assert.deepEqual(f.data().jobs,{});
});
