'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const core=path.resolve(__dirname,'../../TeleBox-Core');
const {buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs'));
const {PluginHost}=require(path.join(core,'dist/v2/host.js'));
const artifact=buildPlugin({id:'uai',packageRoot:path.resolve(__dirname,'../uai'),entry:'v2.ts'}).artifactDir;
const create=require(path.join(artifact,'index.cjs')).default;
async function fixture(t,fetchImpl=async()=>Response.json({choices:[{message:{content:'结论 <安全>'}}]}),legacy){
 const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'mibot-uai-')));if(legacy){await fs.mkdir(path.join(root,'uai'));await fs.writeFile(path.join(root,'uai','config.json'),JSON.stringify(legacy));}
 const edits=[],requests=[];let reply;const raw={peerId:'peer'};const client={async getEntity(){return{firstName:'甲'};},async *iterMessages(){yield{date:Math.floor(Date.now()/1000),message:'第一条',senderId:7n,sender:{firstName:'甲'}};},async sendMessage(){},};
 const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},http:{fetch:async(u,i)=>{requests.push({url:new URL(u),init:i});return fetchImpl(u,i);}},telegram:{async edit(m,text,options){edits.push({text,options});},async reply(){},async invoke(){},async getReply(){return reply;},async withClient(fn,signal){return fn(client,signal);}}});
 await host.load(create());t.after(async()=>{assert.equal((await host.shutdown(1000)).completed,true);await fs.rm(root,{recursive:true,force:true});});
 return{host,root,edits,requests,setReply(v){reply=v;},run(text,message={}){return host.dispatchPrimary({id:1,chatId:'1',senderId:'1',outgoing:true,text,raw,...message});}};
}
test('uai migrates legacy providers once and keeps provider keys secret',async t=>{const legacy={providers:{old:{name:'old',base_url:'https://ai.example.test/base',api_key:'legacy-secret',model:'m',type:'openai',auth_method:'bearer_token'}},default_provider:'old',timeout:20000,collapse:false};const f=await fixture(t,undefined,legacy);const visible=await f.host.readSettings('uai');assert.equal(visible.secretSet.providers,true);assert.equal(visible.values.providers,undefined);assert.equal(visible.values.defaultProvider,'old');await f.host.unload('uai',1000);await f.host.load(create());assert.equal((await f.host.readSettings('uai')).values.defaultProvider,'old');});
test('uai accepts keys only in Saved Messages, validates HTTPS and calls same-host endpoint',async t=>{const f=await fixture(t);await f.run('.uai add p https://ai.example.test key openai');assert.match(f.edits.at(-1).text,/收藏夹/);await f.run('.uai add p http://ai.example.test key openai',{saved:true});assert.match(f.edits.at(-1).text,/执行失败/);await f.run('.uai add p https://ai.example.test/base key openai',{saved:true});f.setReply({id:2,chatId:'1',senderId:'7',outgoing:false,text:'第一条',raw:{senderId:7n,sender:{firstName:'甲'}}});await f.run('.uai zj 1',{saved:true,replyToId:2});assert.equal(f.requests.length,1);assert.equal(f.requests[0].url.href,'https://ai.example.test/base/v1/chat/completions');assert.equal(f.requests[0].init.headers.authorization,'Bearer key');assert.match(f.edits.at(-1).text,/&lt;安全&gt;/);assert.doesNotMatch(f.edits.map(x=>x.text).join('\n'),/\bkey\b/);});
test('uai blocks cross-host redirects and releases resources across reload',async t=>{let calls=0;const f=await fixture(t,async()=>{calls++;return new Response(null,{status:302,headers:{location:'https://evil.example/steal'}});});await f.run('.uai add p https://ai.example.test key openai',{saved:true});f.setReply({id:2,text:'x',raw:{senderId:7n}});await f.run('.uai zj 1',{replyToId:2});assert.equal(calls,1);assert.match(f.edits.at(-1).text,/执行失败/);await f.host.unload('uai',1000);await f.host.load(create());assert.equal(f.host.pluginState('uai'),'active');});
test('uai cancels an in-flight provider request on unload',async t=>{let began;const started=new Promise(resolve=>{began=resolve;});const f=await fixture(t,async(_url,init)=>{began();return new Promise((_resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('private provider detail')),{once:true}));});await f.run('.uai add p https://ai.example.test key openai',{saved:true});f.setReply({id:2,text:'x',raw:{senderId:7n}});const running=f.run('.uai zj 1',{replyToId:2});await started;assert.equal((await f.host.unload('uai',1000)).completed,true);await running;assert.equal(f.host.pluginState('uai'),undefined);assert.doesNotMatch(f.edits.map(x=>x.text).join('\n'),/private provider detail/);});
