'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const core=path.resolve(__dirname,'../../TeleBox-Core');const {buildPlugin}=require(path.join(core,'scripts/build-v2-plugin.cjs'));const {PluginHost}=require(path.join(core,'dist/v2/host.js'));
const artifact=buildPlugin({id:'zpr',packageRoot:path.resolve(__dirname,'../zpr'),entry:'v2.ts'}).artifactDir,create=require(path.join(artifact,'index.cjs')).default;
const api={data:[{pid:123,title:'A < B',width:1000,height:800,urls:{regular:'https://i.pximg.net/image.jpg',original:'https://i.pximg.net/original.jpg'}}]};
async function fixture(t,fetchImpl,legacy){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'mibot-zpr-')));if(legacy){await fs.mkdir(path.join(root,'zpr'));await fs.writeFile(path.join(root,'zpr','zpr_config.json'),JSON.stringify(legacy));}const edits=[],sent=[],requests=[];const raw={peerId:'peer',async delete(){}};const client={async sendFile(peer,options){sent.push({peer,options});}};const host=new PluginHost({storageRoot:root,logger:{info(){},error(){}},http:{fetch:async(u,i)=>{requests.push(new URL(u));return fetchImpl(u,i);}},telegram:{async edit(m,text){edits.push(text);},async reply(){},async invoke(){},async getReply(){},async withClient(fn,signal){return fn(client,signal);}}});await host.load(create());t.after(async()=>{assert.equal((await host.shutdown(1000)).completed,true);await fs.rm(root,{recursive:true,force:true});});return{host,edits,sent,requests,run:(text)=>host.dispatchPrimary({id:1,chatId:'1',senderId:'1',outgoing:true,text,raw})};}
test('zpr migrates legacy proxy idempotently and validates settings',async t=>{const f=await fixture(t,async()=>assert.fail('network'),{zpr_proxy_host:'i.pixiv.cat'});assert.equal((await f.host.readSettings('zpr')).values.proxyHost,'i.pixiv.cat');await assert.rejects(f.host.patchSettings('zpr',{proxyHost:'evil.test'}));await f.host.unload('zpr',1000);await f.host.load(create());assert.equal((await f.host.readSettings('zpr')).values.proxyHost,'i.pixiv.cat');});
test('zpr validates API data, bounds image download and sends escaped media',async t=>{const f=await fixture(t,async u=>new URL(u).hostname==='api.lolicon.app'?Response.json(api):new Response(Buffer.from('image'),{status:200,headers:{'content-type':'image/jpeg'}}));await f.run('.zpr 标签 1 r18');assert.equal(f.sent.length,1);assert.equal(f.sent[0].options.spoiler,true);assert.match(f.sent[0].options.caption,/A &lt; B/);assert.deepEqual(f.requests.map(x=>x.hostname),['api.lolicon.app','i.pximg.net']);});
test('zpr blocks redirect escapes and reports external failure',async t=>{let calls=0;const f=await fixture(t,async u=>{calls++;if(new URL(u).hostname==='api.lolicon.app')return new Response(null,{status:302,headers:{location:'https://evil.example/data'}});return new Response('x');});await f.run('.zpr');assert.equal(calls,1);assert.match(f.edits.at(-1),/获取图片失败/);assert.equal(f.sent.length,0);});
test('zpr retries only allowlisted image hosts and reloads cleanly',async t=>{const f=await fixture(t,async u=>{const host=new URL(u).hostname;if(host==='api.lolicon.app')return Response.json(api);if(host==='i.pximg.net')throw Object.assign(new Error('secret'),{code:'ECONNRESET'});return new Response(Buffer.from('ok'),{headers:{'content-type':'image/jpeg'}});});await f.run('.zpr');assert.deepEqual(f.requests.map(x=>x.hostname).slice(0,3),['api.lolicon.app','i.pximg.net','i.pixiv.cat']);assert.equal((await f.host.readSettings('zpr')).values.proxyHost,'i.pixiv.cat');await f.host.unload('zpr',1000);await f.host.load(create());assert.equal(f.host.pluginState('zpr'),'active');});
test('zpr cancels an in-flight API request on unload',async t=>{let began;const started=new Promise(resolve=>{began=resolve;});const f=await fixture(t,async(_url,init)=>{began();return new Promise((_resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('private network detail')),{once:true}));});const running=f.run('.zpr');await started;assert.equal((await f.host.unload('zpr',1000)).completed,true);await running;assert.equal(f.host.pluginState('zpr'),undefined);assert.doesNotMatch(f.edits.join('\n'),/private network detail/);});
