import {renderHelp as renderPluginHelp} from "./v2/help";
import path from "node:path";
import {createReadStream} from "node:fs";
import {open,readFile,rename,writeFile} from "node:fs/promises";
import {Readable} from "node:stream";
import {definePlugin,type MessageEnvelope,type PluginContext} from "telebox/sdk";
type State={schemaVersion:1;username:string;password:string;defaultPath:string;legacyImported:boolean;[key:string]:unknown};
const defaults:State={schemaVersion:1,username:"",password:"",defaultPath:"",legacyImported:false};
const store=(c:PluginContext)=>c.storage.json<State>("credentials-v2.json",defaults);
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[x]!);
const INSTALL="/opt/openlist",BIN=`${INSTALL}/openlist`,SERVICE="/etc/systemd/system/openlist.service",BACKUPS="/opt/openlist_backups";
const commands={systemctl:"/usr/bin/systemctl",mkdir:"/bin/mkdir",rm:"/bin/rm",cp:"/bin/cp",tar:"/usr/bin/tar",install:"/usr/bin/install",chmod:"/bin/chmod",date:"/bin/date"} as const;
async function run(c:PluginContext,cmd:keyof typeof commands,args:string[],options:any={}){return c.processes.run(commands[cmd],args,{timeoutMs:Math.min(options.timeoutMs??30_000,120_000),maxOutputBytes:256*1024,...options});}
async function migrate(c:PluginContext){const current=await store(c).read();if(current.legacyImported)return;let legacy:any={};try{legacy=JSON.parse(await (await import("node:fs/promises")).readFile(c.files.dataPath("credentials.json"),"utf8"));}catch{}await store(c).update(v=>({...v,username:v.username||String(legacy.username??""),password:v.password||String(legacy.password??""),defaultPath:v.defaultPath||String(legacy.defaultPath??""),legacyImported:true}));}
async function api(c:PluginContext,url:string,init:RequestInit){return c.http.withResponse(url,init,async(r,s)=>{const reader=r.body?.getReader();if(!reader)throw new Error("OpenList 返回空响应");const chunks:Buffer[]=[];let total=0;try{for(;;){s.throwIfAborted();const x=await reader.read();if(x.done)break;total+=x.value.length;if(total>1024*1024)throw new Error("OpenList 响应过大");chunks.push(Buffer.from(x.value));}}finally{reader.releaseLock();}let data:any;try{data=JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new Error("OpenList 返回无效 JSON");}if(!r.ok)throw new Error(`HTTP ${r.status}`);if(data?.code!==200)throw new Error(typeof data?.message==="string"?"OpenList 操作失败":"OpenList 响应结构异常");return data.data;},{timeoutMs:30_000,redirects:{allowedHosts:["127.0.0.1"],maxRedirects:0}});}
async function token(c:PluginContext){const s=await store(c).read();if(!s.username||!s.password)throw new Error("请先配置 OpenList 账号");const data=await api(c,"http://127.0.0.1:5244/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:s.username,password:s.password})});if(typeof data?.token!=="string"||!data.token)throw new Error("OpenList 登录响应无令牌");return data.token;}
const safePath=(v:string)=>{const normalized=path.posix.normalize(v.startsWith("/")?v:`/${v}`);if(!normalized.startsWith("/")||normalized.includes("\0"))throw new Error("目标路径无效");return normalized;};
async function status(c:PluginContext){try{const r=await run(c,"systemctl",["is-active","openlist"],{timeoutMs:10_000});return r.stdout.toString().trim()==="active"?"OpenList 服务运行中。":"OpenList 服务未运行。";}catch{return"OpenList 服务未运行或未安装。";}}
async function admin(c:PluginContext,args:readonly string[]){const sub=args[0],value=args[1];if(!["setuser","setpass","random"].includes(sub??""))throw new Error("用法：op admin setuser|setpass|random");const command=sub==="setuser"?["admin","setuser",value??""]:sub==="setpass"?["admin","set",value??""]:["admin","random"];if(command.at(-1)==="")throw new Error("缺少新凭据");const out=(await c.processes.run(BIN,command,{cwd:INSTALL,timeoutMs:30_000,maxOutputBytes:64*1024})).stdout.toString();let username=sub==="setuser"?value??"":"",password=sub==="setpass"?value??"":"";if(sub==="random"){username=out.match(/username:\s*(\S+)/i)?.[1]??"";password=out.match(/password:\s*(\S+)/i)?.[1]??"";}if(username||password)await store(c).update(v=>({...v,username:username||v.username,password:password||v.password}));return"管理命令执行成功，凭据已同步且密码不回显。";}
async function setPort(c:PluginContext,value:string|undefined){const port=Number(value);if(!Number.isInteger(port)||port<1||port>65535)throw new Error("端口必须是 1 到 65535 的整数");const config=`${INSTALL}/data/config.json`,backup=`${config}.previous`,temporary=`${config}.mibot-new`;let stopped=false;await run(c,"cp",["-a",config,backup]);try{const document=JSON.parse(await readFile(config,"utf8"));if(!document?.scheme||typeof document.scheme!=="object")throw new Error("OpenList 配置结构异常");document.scheme.http_port=port;await writeFile(temporary,`${JSON.stringify(document,null,2)}\n`,{mode:0o600,flag:"wx"});await run(c,"systemctl",["stop","openlist"]);stopped=true;await rename(temporary,config);await run(c,"systemctl",["start","openlist"]);return`OpenList 端口已修改为 ${port}。`;}catch(error){await run(c,"rm",["-f",temporary]).catch(()=>undefined);if(stopped){await run(c,"cp",["-a",backup,config]).catch(()=>undefined);await run(c,"systemctl",["start","openlist"]).catch(()=>undefined);}throw error;}}
async function save(c:PluginContext,m:MessageEnvelope,target?:string){const reply=await c.telegram.getReply(m);const raw:any=reply?.raw;if(!raw?.media)throw new Error("请回复媒体文件");const name=String(raw?.file?.name??raw?.document?.attributes?.find((x:any)=>x?.className==="DocumentAttributeFilename")?.fileName??`media_${reply!.id}`).replace(/[\\/:*?"<>|\x00-\x1f]/g,"_").slice(0,120);const state=await store(c).read(),destination=safePath(path.posix.join(target??state.defaultPath??"/",name)),auth=await token(c);await c.files.withTemp(async(dir,signal)=>{const file=path.join(dir,name),handle=await open(file,"wx");let total=0;try{await c.telegram.withClient(async(client:any)=>{for await(const chunk of client.iterDownload(raw.media,{})){signal.throwIfAborted();total+=chunk.length;if(total>2*1024*1024*1024)throw new Error("媒体超过 2 GiB");await handle.write(chunk);}});}finally{await handle.close();}const stream=Readable.toWeb(createReadStream(file));await api(c,"http://127.0.0.1:5244/api/fs/put",{method:"PUT",headers:{authorization:auth,"file-path":encodeURIComponent(destination),"content-type":"application/octet-stream","as-task":"false"},body:stream as never,...({duplex:"half"} as any)});});return`文件已上传到 <code>${esc(destination)}</code>`;}
async function installOrUpdate(c:PluginContext,update:boolean){if(process.platform!=="linux")throw new Error("此操作仅支持 Linux systemd");const arch:{[k:string]:string}={x64:"amd64",arm64:"arm64",s390x:"s390x",loong64:"loong64"},mapped=arch[process.arch];if(!mapped)throw new Error("不支持当前架构");let snapshot=false;try{await c.files.withTemp(async dir=>{const archive=path.join(dir,"openlist.tar.gz"),service=path.join(dir,"openlist.service"),url=new URL(`https://github.com/OpenListTeam/OpenList/releases/latest/download/openlist-linux-musl-${mapped}.tar.gz`);const bytes=await c.http.withResponse(url,{},async(r,s)=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);const reader=r.body?.getReader();if(!reader)throw new Error("下载为空");const file=await open(archive,"wx");let total=0;try{for(;;){s.throwIfAborted();const x=await reader.read();if(x.done)break;total+=x.value.length;if(total>256*1024*1024)throw new Error("安装包过大");await file.write(x.value);}}finally{await file.close();reader.releaseLock();}return total;},{timeoutMs:120_000,redirects:{allowedHosts:["github.com","objects.githubusercontent.com","release-assets.githubusercontent.com"],maxRedirects:5}});if(!bytes)throw new Error("下载为空");if(update){await run(c,"cp",["-a",BIN,`${BIN}.previous`]);snapshot=true;await run(c,"systemctl",["stop","openlist"],{timeoutMs:20_000});}await run(c,"mkdir",["-p",INSTALL]);await run(c,"tar",["-xzf",archive,"-C",INSTALL],{timeoutMs:120_000});await run(c,"chmod",["0755",BIN]);await writeFile(service,`[Unit]\nDescription=OpenList service\nAfter=network.target\n\n[Service]\nType=simple\nWorkingDirectory=${INSTALL}\nExecStart=${BIN} server\nRestart=on-failure\n\n[Install]\nWantedBy=multi-user.target\n`);await run(c,"install",["-m","0644",service,SERVICE]);await run(c,"systemctl",["daemon-reload"]);await run(c,"systemctl",["enable","--now","openlist"],{timeoutMs:30_000});});}catch(error){if(update&&snapshot){await run(c,"cp",["-a",`${BIN}.previous`,BIN]).catch(()=>undefined);await run(c,"systemctl",["start","openlist"]).catch(()=>undefined);}throw error;}return update?"OpenList 更新完成。":"OpenList 安装完成。";}
async function command(m:MessageEnvelope,args:readonly string[],prefix:string,c:PluginContext){const sub=args[0]?.toLowerCase()??"help";try{if((sub==="login"||sub==="admin"&&["setpass","random"].includes(args[1]??""))&&!m.saved)throw new Error("密码仅限在收藏夹中设置");let result:string;if(sub==="status")result=await status(c);else if(sub==="login"){if(!args[1]||!args[2])throw new Error("用法：op login 用户 密码");await store(c).update(v=>({...v,username:args[1]!,password:args.slice(2).join(" ")}));result="OpenList 账号已保存。";}else if(sub==="setdefault"){const value=args.slice(1).join(" ");if(value)safePath(value);await store(c).update(v=>({...v,defaultPath:value}));result="默认上传路径已更新。";}else if(sub==="save")result=await save(c,m,args[1]);else if(sub==="admin")result=await admin(c,args.slice(1));else if(sub==="setport")result=await setPort(c,args[1]);else if(sub==="install"||sub==="update")result=await installOrUpdate(c,sub==="update");else if(sub==="uninstall"){await run(c,"systemctl",["disable","--now","openlist"]).catch(()=>undefined);await run(c,"rm",["-f",SERVICE]);await run(c,"systemctl",["daemon-reload"]);result="OpenList 服务已卸载，数据目录保留。";}else if(sub==="backup"){await run(c,"mkdir",["-p",BACKUPS]);const stamp=(await run(c,"date",["+%Y%m%d_%H%M%S"])).stdout.toString().trim(),directory=`${BACKUPS}/backup_${stamp}`;await run(c,"mkdir",["-p",directory]);await run(c,"cp",["-a",`${INSTALL}/data`,directory],{timeoutMs:120_000});result=`备份完成：<code>backup_${esc(stamp)}</code>`;}else if(sub==="restore"){if(!/^[A-Za-z0-9._-]+$/.test(args[1]??""))throw new Error("请提供安全的备份名");await run(c,"systemctl",["stop","openlist"]);try{await run(c,"cp",["-a",`${BACKUPS}/${args[1]}/data`,INSTALL],{timeoutMs:120_000});await run(c,"systemctl",["start","openlist"]);}catch(e){await run(c,"systemctl",["start","openlist"]).catch(()=>undefined);throw e;}result="OpenList 数据恢复完成。";}else result=`<b>OpenList 管理</b>\n<code>${esc(prefix)}op status|install|update|uninstall|backup|restore|setport</code>\n<code>${esc(prefix)}op login 用户 密码</code>\n<code>${esc(prefix)}op save [路径]</code>（回复媒体）\n<code>${esc(prefix)}op admin setuser|setpass|random</code>`;await c.telegram.edit(m,result,{parseMode:"html"});}catch(e){if(!c.signal.aborted)await c.telegram.edit(m,`❌ ${esc(e instanceof Error?e.message:"OpenList 操作失败")}`,{parseMode:"html"});}}
export default function createOpenlist(){const definition={description:"管理 OpenList 服务并上传 Telegram 媒体",async handle(i:any,c:PluginContext){await command(i.message,i.args,i.prefix,c);}};return definePlugin({renderHelp: renderPluginHelp, apiVersion:1,id:"openlist",description:"OpenList 安装、凭据、备份和媒体上传",resources:{processes:{concurrency:1,queueCapacity:2,timeoutMs:120_000,maxOutputBytes:262144}},commands:{openlist:definition,op:definition},settings:c=>({id:"openlist",title:"OpenList",category:"插件配置",icon:"📁",getSchema:()=>[{key:"username",label:"用户名",type:"string"},{key:"password",label:"密码",type:"password",secret:true},{key:"defaultPath",label:"默认上传路径",type:"string"}],getValues:async()=>{const v=await store(c).read();return{username:v.username,password:v.password,defaultPath:v.defaultPath};},async setValues(p){await store(c).update(v=>{const defaultPath=typeof p.defaultPath==="string"?p.defaultPath:v.defaultPath;if(defaultPath)safePath(defaultPath);return{...v,username:typeof p.username==="string"?p.username:v.username,password:typeof p.password==="string"?p.password:v.password,defaultPath};});}}),setup:migrate});}
